/*
 * generated by Xtext 2.15.0
 */
package xproject.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.UnorderedGroup;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class XHDLGrammarAccess extends AbstractGrammarElementFinder {
	
	public class XhdlElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xproject.XHDL.xhdl");
		private final Assignment cPackagesAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cPackagesXPackageParserRuleCall_0 = (RuleCall)cPackagesAssignment.eContents().get(0);
		
		//xhdl:
		//	packages+=XPackage*;
		@Override public ParserRule getRule() { return rule; }
		
		//packages+=XPackage*
		public Assignment getPackagesAssignment() { return cPackagesAssignment; }
		
		//XPackage
		public RuleCall getPackagesXPackageParserRuleCall_0() { return cPackagesXPackageParserRuleCall_0; }
	}
	public class XPackageRefElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xproject.XHDL.XPackageRef");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cXPackageRefAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//XPackageRef:
		//	{XPackageRef} name=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//{XPackageRef} name=ID
		public Group getGroup() { return cGroup; }
		
		//{XPackageRef}
		public Action getXPackageRefAction_0() { return cXPackageRefAction_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
	}
	public class XPackageElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xproject.XHDL.XPackage");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPackageKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cIsKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cXisAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cXisXElementParserRuleCall_3_0 = (RuleCall)cXisAssignment_3.eContents().get(0);
		private final Keyword cEndKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final UnorderedGroup cUnorderedGroup_5 = (UnorderedGroup)cGroup.eContents().get(5);
		private final Assignment cXendAssignment_5_0 = (Assignment)cUnorderedGroup_5.eContents().get(0);
		private final RuleCall cXendXPackageRefParserRuleCall_5_0_0 = (RuleCall)cXendAssignment_5_0.eContents().get(0);
		private final Keyword cSemicolonKeyword_5_1 = (Keyword)cUnorderedGroup_5.eContents().get(1);
		
		//XPackage:
		//	'package' name=ID 'is'
		//	xis+=XElement*
		//	'end' (xend=XPackageRef & ';');
		@Override public ParserRule getRule() { return rule; }
		
		//'package' name=ID 'is' xis+=XElement* 'end' (xend=XPackageRef & ';')
		public Group getGroup() { return cGroup; }
		
		//'package'
		public Keyword getPackageKeyword_0() { return cPackageKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//'is'
		public Keyword getIsKeyword_2() { return cIsKeyword_2; }
		
		//xis+=XElement*
		public Assignment getXisAssignment_3() { return cXisAssignment_3; }
		
		//XElement
		public RuleCall getXisXElementParserRuleCall_3_0() { return cXisXElementParserRuleCall_3_0; }
		
		//'end'
		public Keyword getEndKeyword_4() { return cEndKeyword_4; }
		
		//xend=XPackageRef & ';'
		public UnorderedGroup getUnorderedGroup_5() { return cUnorderedGroup_5; }
		
		//xend=XPackageRef
		public Assignment getXendAssignment_5_0() { return cXendAssignment_5_0; }
		
		//XPackageRef
		public RuleCall getXendXPackageRefParserRuleCall_5_0_0() { return cXendXPackageRefParserRuleCall_5_0_0; }
		
		//';'
		public Keyword getSemicolonKeyword_5_1() { return cSemicolonKeyword_5_1; }
	}
	public class XTypeRefElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xproject.XHDL.XTypeRef");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cXTypeRefAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//XTypeRef:
		//	{XTypeRef} name=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//{XTypeRef} name=ID
		public Group getGroup() { return cGroup; }
		
		//{XTypeRef}
		public Action getXTypeRefAction_0() { return cXTypeRefAction_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
	}
	public class XElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xproject.XHDL.XElement");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cXTypeParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cXSignalParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cXSubTypeParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cXAttributeParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cXImpureParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cXFunctionParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		private final RuleCall cXProcedureParserRuleCall_6 = (RuleCall)cAlternatives.eContents().get(6);
		
		//XElement:
		//	XType | XSignal | XSubType | XAttribute | XImpure | XFunction | XProcedure;
		@Override public ParserRule getRule() { return rule; }
		
		//XType | XSignal | XSubType | XAttribute | XImpure | XFunction | XProcedure
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//XType
		public RuleCall getXTypeParserRuleCall_0() { return cXTypeParserRuleCall_0; }
		
		//XSignal
		public RuleCall getXSignalParserRuleCall_1() { return cXSignalParserRuleCall_1; }
		
		//XSubType
		public RuleCall getXSubTypeParserRuleCall_2() { return cXSubTypeParserRuleCall_2; }
		
		//XAttribute
		public RuleCall getXAttributeParserRuleCall_3() { return cXAttributeParserRuleCall_3; }
		
		//XImpure
		public RuleCall getXImpureParserRuleCall_4() { return cXImpureParserRuleCall_4; }
		
		//XFunction
		public RuleCall getXFunctionParserRuleCall_5() { return cXFunctionParserRuleCall_5; }
		
		//XProcedure
		public RuleCall getXProcedureParserRuleCall_6() { return cXProcedureParserRuleCall_6; }
	}
	public class XAttributeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xproject.XHDL.XAttribute");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cXAttributeAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cAttributeKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final UnorderedGroup cUnorderedGroup_2 = (UnorderedGroup)cGroup.eContents().get(2);
		private final Assignment cNameAssignment_2_0 = (Assignment)cUnorderedGroup_2.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_2_0_0 = (RuleCall)cNameAssignment_2_0.eContents().get(0);
		private final Keyword cColonKeyword_2_1 = (Keyword)cUnorderedGroup_2.eContents().get(1);
		private final Assignment cXtypeAssignment_2_2 = (Assignment)cUnorderedGroup_2.eContents().get(2);
		private final RuleCall cXtypeXTypeRefParserRuleCall_2_2_0 = (RuleCall)cXtypeAssignment_2_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_2_3 = (Keyword)cUnorderedGroup_2.eContents().get(3);
		
		//XAttribute:
		//	{XAttribute} 'attribute' (name=ID & ':' & xtype=XTypeRef & ';');
		@Override public ParserRule getRule() { return rule; }
		
		//{XAttribute} 'attribute' (name=ID & ':' & xtype=XTypeRef & ';')
		public Group getGroup() { return cGroup; }
		
		//{XAttribute}
		public Action getXAttributeAction_0() { return cXAttributeAction_0; }
		
		//'attribute'
		public Keyword getAttributeKeyword_1() { return cAttributeKeyword_1; }
		
		//name=ID & ':' & xtype=XTypeRef & ';'
		public UnorderedGroup getUnorderedGroup_2() { return cUnorderedGroup_2; }
		
		//name=ID
		public Assignment getNameAssignment_2_0() { return cNameAssignment_2_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0_0() { return cNameIDTerminalRuleCall_2_0_0; }
		
		//':'
		public Keyword getColonKeyword_2_1() { return cColonKeyword_2_1; }
		
		//xtype=XTypeRef
		public Assignment getXtypeAssignment_2_2() { return cXtypeAssignment_2_2; }
		
		//XTypeRef
		public RuleCall getXtypeXTypeRefParserRuleCall_2_2_0() { return cXtypeXTypeRefParserRuleCall_2_2_0; }
		
		//';'
		public Keyword getSemicolonKeyword_2_3() { return cSemicolonKeyword_2_3; }
	}
	public class XSubTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xproject.XHDL.XSubType");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cXSubTypeAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cSubtypeKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cIsKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final UnorderedGroup cUnorderedGroup_4 = (UnorderedGroup)cGroup.eContents().get(4);
		private final Group cGroup_4_0 = (Group)cUnorderedGroup_4.eContents().get(0);
		private final Assignment cXisAssignment_4_0_0 = (Assignment)cGroup_4_0.eContents().get(0);
		private final RuleCall cXisXTypeRefParserRuleCall_4_0_0_0 = (RuleCall)cXisAssignment_4_0_0.eContents().get(0);
		private final Assignment cXrangeAssignment_4_0_1 = (Assignment)cGroup_4_0.eContents().get(1);
		private final RuleCall cXrangeXRangeParserRuleCall_4_0_1_0 = (RuleCall)cXrangeAssignment_4_0_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_4_1 = (Keyword)cUnorderedGroup_4.eContents().get(1);
		
		//XSubType:
		//	{XSubType} 'subtype' name=ID 'is' (xis=XTypeRef xrange=XRange? & ';');
		@Override public ParserRule getRule() { return rule; }
		
		//{XSubType} 'subtype' name=ID 'is' (xis=XTypeRef xrange=XRange? & ';')
		public Group getGroup() { return cGroup; }
		
		//{XSubType}
		public Action getXSubTypeAction_0() { return cXSubTypeAction_0; }
		
		//'subtype'
		public Keyword getSubtypeKeyword_1() { return cSubtypeKeyword_1; }
		
		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }
		
		//'is'
		public Keyword getIsKeyword_3() { return cIsKeyword_3; }
		
		//xis=XTypeRef xrange=XRange? & ';'
		public UnorderedGroup getUnorderedGroup_4() { return cUnorderedGroup_4; }
		
		//xis=XTypeRef xrange=XRange?
		public Group getGroup_4_0() { return cGroup_4_0; }
		
		//xis=XTypeRef
		public Assignment getXisAssignment_4_0_0() { return cXisAssignment_4_0_0; }
		
		//XTypeRef
		public RuleCall getXisXTypeRefParserRuleCall_4_0_0_0() { return cXisXTypeRefParserRuleCall_4_0_0_0; }
		
		//xrange=XRange?
		public Assignment getXrangeAssignment_4_0_1() { return cXrangeAssignment_4_0_1; }
		
		//XRange
		public RuleCall getXrangeXRangeParserRuleCall_4_0_1_0() { return cXrangeXRangeParserRuleCall_4_0_1_0; }
		
		//';'
		public Keyword getSemicolonKeyword_4_1() { return cSemicolonKeyword_4_1; }
	}
	public class XSignalElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xproject.XHDL.XSignal");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cXSignalAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cSignalKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final UnorderedGroup cUnorderedGroup_2 = (UnorderedGroup)cGroup.eContents().get(2);
		private final Assignment cNameAssignment_2_0 = (Assignment)cUnorderedGroup_2.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_2_0_0 = (RuleCall)cNameAssignment_2_0.eContents().get(0);
		private final Group cGroup_2_1 = (Group)cUnorderedGroup_2.eContents().get(1);
		private final Keyword cColonKeyword_2_1_0 = (Keyword)cGroup_2_1.eContents().get(0);
		private final Assignment cXtypeAssignment_2_1_1 = (Assignment)cGroup_2_1.eContents().get(1);
		private final RuleCall cXtypeXTypeRefParserRuleCall_2_1_1_0 = (RuleCall)cXtypeAssignment_2_1_1.eContents().get(0);
		private final UnorderedGroup cUnorderedGroup_2_2 = (UnorderedGroup)cUnorderedGroup_2.eContents().get(2);
		private final Keyword cSemicolonEqualsSignKeyword_2_2_0 = (Keyword)cUnorderedGroup_2_2.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_2_2_1 = (RuleCall)cUnorderedGroup_2_2.eContents().get(1);
		private final Keyword cSemicolonKeyword_2_3 = (Keyword)cUnorderedGroup_2.eContents().get(3);
		
		//XSignal:
		//	{XSignal} 'signal' (name=ID & ':' xtype=XTypeRef & (';=' & ID)? & ';');
		@Override public ParserRule getRule() { return rule; }
		
		//{XSignal} 'signal' (name=ID & ':' xtype=XTypeRef & (';=' & ID)? & ';')
		public Group getGroup() { return cGroup; }
		
		//{XSignal}
		public Action getXSignalAction_0() { return cXSignalAction_0; }
		
		//'signal'
		public Keyword getSignalKeyword_1() { return cSignalKeyword_1; }
		
		//name=ID & ':' xtype=XTypeRef & (';=' & ID)? & ';'
		public UnorderedGroup getUnorderedGroup_2() { return cUnorderedGroup_2; }
		
		//name=ID
		public Assignment getNameAssignment_2_0() { return cNameAssignment_2_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0_0() { return cNameIDTerminalRuleCall_2_0_0; }
		
		//':' xtype=XTypeRef
		public Group getGroup_2_1() { return cGroup_2_1; }
		
		//':'
		public Keyword getColonKeyword_2_1_0() { return cColonKeyword_2_1_0; }
		
		//xtype=XTypeRef
		public Assignment getXtypeAssignment_2_1_1() { return cXtypeAssignment_2_1_1; }
		
		//XTypeRef
		public RuleCall getXtypeXTypeRefParserRuleCall_2_1_1_0() { return cXtypeXTypeRefParserRuleCall_2_1_1_0; }
		
		//(';=' & ID)?
		public UnorderedGroup getUnorderedGroup_2_2() { return cUnorderedGroup_2_2; }
		
		//';='
		public Keyword getSemicolonEqualsSignKeyword_2_2_0() { return cSemicolonEqualsSignKeyword_2_2_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_2_2_1() { return cIDTerminalRuleCall_2_2_1; }
		
		//';'
		public Keyword getSemicolonKeyword_2_3() { return cSemicolonKeyword_2_3; }
	}
	public class XTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xproject.XHDL.XType");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cXTypeAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cTypeKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameIDTerminalRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cIsKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final UnorderedGroup cUnorderedGroup_4 = (UnorderedGroup)cGroup.eContents().get(4);
		private final Alternatives cAlternatives_4_0 = (Alternatives)cUnorderedGroup_4.eContents().get(0);
		private final Assignment cXenumsAssignment_4_0_0 = (Assignment)cAlternatives_4_0.eContents().get(0);
		private final RuleCall cXenumsXEnumsParserRuleCall_4_0_0_0 = (RuleCall)cXenumsAssignment_4_0_0.eContents().get(0);
		private final Assignment cXrangeAssignment_4_0_1 = (Assignment)cAlternatives_4_0.eContents().get(1);
		private final RuleCall cXrangeXRangeParserRuleCall_4_0_1_0 = (RuleCall)cXrangeAssignment_4_0_1.eContents().get(0);
		private final Assignment cXarrayAssignment_4_0_2 = (Assignment)cAlternatives_4_0.eContents().get(2);
		private final RuleCall cXarrayXArrayParserRuleCall_4_0_2_0 = (RuleCall)cXarrayAssignment_4_0_2.eContents().get(0);
		private final Assignment cXaccessAssignment_4_0_3 = (Assignment)cAlternatives_4_0.eContents().get(3);
		private final RuleCall cXaccessXAccessParserRuleCall_4_0_3_0 = (RuleCall)cXaccessAssignment_4_0_3.eContents().get(0);
		private final Assignment cXfileOfAssignment_4_0_4 = (Assignment)cAlternatives_4_0.eContents().get(4);
		private final RuleCall cXfileOfXFileOfParserRuleCall_4_0_4_0 = (RuleCall)cXfileOfAssignment_4_0_4.eContents().get(0);
		private final Keyword cSemicolonKeyword_4_1 = (Keyword)cUnorderedGroup_4.eContents().get(1);
		
		//XType:
		//	{XType} 'type' name=ID 'is' ((xenums=XEnums | xrange=XRange | xarray=XArray | xaccess=XAccess | xfileOf=XFileOf) &
		//	';');
		@Override public ParserRule getRule() { return rule; }
		
		//{XType} 'type' name=ID 'is' ((xenums=XEnums | xrange=XRange | xarray=XArray | xaccess=XAccess | xfileOf=XFileOf) & ';')
		public Group getGroup() { return cGroup; }
		
		//{XType}
		public Action getXTypeAction_0() { return cXTypeAction_0; }
		
		//'type'
		public Keyword getTypeKeyword_1() { return cTypeKeyword_1; }
		
		//name=ID
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0() { return cNameIDTerminalRuleCall_2_0; }
		
		//'is'
		public Keyword getIsKeyword_3() { return cIsKeyword_3; }
		
		//(xenums=XEnums | xrange=XRange | xarray=XArray | xaccess=XAccess | xfileOf=XFileOf) & ';'
		public UnorderedGroup getUnorderedGroup_4() { return cUnorderedGroup_4; }
		
		//(xenums=XEnums | xrange=XRange | xarray=XArray | xaccess=XAccess | xfileOf=XFileOf)
		public Alternatives getAlternatives_4_0() { return cAlternatives_4_0; }
		
		//xenums=XEnums
		public Assignment getXenumsAssignment_4_0_0() { return cXenumsAssignment_4_0_0; }
		
		//XEnums
		public RuleCall getXenumsXEnumsParserRuleCall_4_0_0_0() { return cXenumsXEnumsParserRuleCall_4_0_0_0; }
		
		//xrange=XRange
		public Assignment getXrangeAssignment_4_0_1() { return cXrangeAssignment_4_0_1; }
		
		//XRange
		public RuleCall getXrangeXRangeParserRuleCall_4_0_1_0() { return cXrangeXRangeParserRuleCall_4_0_1_0; }
		
		//xarray=XArray
		public Assignment getXarrayAssignment_4_0_2() { return cXarrayAssignment_4_0_2; }
		
		//XArray
		public RuleCall getXarrayXArrayParserRuleCall_4_0_2_0() { return cXarrayXArrayParserRuleCall_4_0_2_0; }
		
		//xaccess=XAccess
		public Assignment getXaccessAssignment_4_0_3() { return cXaccessAssignment_4_0_3; }
		
		//XAccess
		public RuleCall getXaccessXAccessParserRuleCall_4_0_3_0() { return cXaccessXAccessParserRuleCall_4_0_3_0; }
		
		//xfileOf=XFileOf
		public Assignment getXfileOfAssignment_4_0_4() { return cXfileOfAssignment_4_0_4; }
		
		//XFileOf
		public RuleCall getXfileOfXFileOfParserRuleCall_4_0_4_0() { return cXfileOfXFileOfParserRuleCall_4_0_4_0; }
		
		//';'
		public Keyword getSemicolonKeyword_4_1() { return cSemicolonKeyword_4_1; }
	}
	public class XArrayElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xproject.XHDL.XArray");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cXArrayAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cArrayKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final UnorderedGroup cUnorderedGroup_2 = (UnorderedGroup)cGroup.eContents().get(2);
		private final Keyword cLeftParenthesisKeyword_2_0 = (Keyword)cUnorderedGroup_2.eContents().get(0);
		private final Group cGroup_2_1 = (Group)cUnorderedGroup_2.eContents().get(1);
		private final Assignment cXrangeAssignment_2_1_0 = (Assignment)cGroup_2_1.eContents().get(0);
		private final RuleCall cXrangeXTypeRefParserRuleCall_2_1_0_0 = (RuleCall)cXrangeAssignment_2_1_0.eContents().get(0);
		private final Keyword cRangeKeyword_2_1_1 = (Keyword)cGroup_2_1.eContents().get(1);
		private final Keyword cLessThanSignGreaterThanSignKeyword_2_1_2 = (Keyword)cGroup_2_1.eContents().get(2);
		private final Keyword cRightParenthesisKeyword_2_2 = (Keyword)cUnorderedGroup_2.eContents().get(2);
		private final Keyword cOfKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cXofAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cXofXTypeRefParserRuleCall_4_0 = (RuleCall)cXofAssignment_4.eContents().get(0);
		
		//XArray:
		//	{XArray} 'array' ('(' & xrange=XTypeRef 'range' '<>' & ')') 'of' xof=XTypeRef;
		@Override public ParserRule getRule() { return rule; }
		
		//{XArray} 'array' ('(' & xrange=XTypeRef 'range' '<>' & ')') 'of' xof=XTypeRef
		public Group getGroup() { return cGroup; }
		
		//{XArray}
		public Action getXArrayAction_0() { return cXArrayAction_0; }
		
		//'array'
		public Keyword getArrayKeyword_1() { return cArrayKeyword_1; }
		
		//'(' & xrange=XTypeRef 'range' '<>' & ')'
		public UnorderedGroup getUnorderedGroup_2() { return cUnorderedGroup_2; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_2_0() { return cLeftParenthesisKeyword_2_0; }
		
		//xrange=XTypeRef 'range' '<>'
		public Group getGroup_2_1() { return cGroup_2_1; }
		
		//xrange=XTypeRef
		public Assignment getXrangeAssignment_2_1_0() { return cXrangeAssignment_2_1_0; }
		
		//XTypeRef
		public RuleCall getXrangeXTypeRefParserRuleCall_2_1_0_0() { return cXrangeXTypeRefParserRuleCall_2_1_0_0; }
		
		//'range'
		public Keyword getRangeKeyword_2_1_1() { return cRangeKeyword_2_1_1; }
		
		//'<>'
		public Keyword getLessThanSignGreaterThanSignKeyword_2_1_2() { return cLessThanSignGreaterThanSignKeyword_2_1_2; }
		
		//')'
		public Keyword getRightParenthesisKeyword_2_2() { return cRightParenthesisKeyword_2_2; }
		
		//'of'
		public Keyword getOfKeyword_3() { return cOfKeyword_3; }
		
		//xof=XTypeRef
		public Assignment getXofAssignment_4() { return cXofAssignment_4; }
		
		//XTypeRef
		public RuleCall getXofXTypeRefParserRuleCall_4_0() { return cXofXTypeRefParserRuleCall_4_0; }
	}
	public class XRangeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xproject.XHDL.XRange");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cXRangeAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cRangeKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cXfromAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cXfromXRangeValueParserRuleCall_2_0 = (RuleCall)cXfromAssignment_2.eContents().get(0);
		private final Keyword cToKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cXtoAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cXtoXRangeValueParserRuleCall_4_0 = (RuleCall)cXtoAssignment_4.eContents().get(0);
		private final Assignment cXunitsAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cXunitsXUnitsParserRuleCall_5_0 = (RuleCall)cXunitsAssignment_5.eContents().get(0);
		
		//XRange:
		//	{XRange} 'range' xfrom=XRangeValue 'to' xto=XRangeValue xunits=XUnits?;
		@Override public ParserRule getRule() { return rule; }
		
		//{XRange} 'range' xfrom=XRangeValue 'to' xto=XRangeValue xunits=XUnits?
		public Group getGroup() { return cGroup; }
		
		//{XRange}
		public Action getXRangeAction_0() { return cXRangeAction_0; }
		
		//'range'
		public Keyword getRangeKeyword_1() { return cRangeKeyword_1; }
		
		//xfrom=XRangeValue
		public Assignment getXfromAssignment_2() { return cXfromAssignment_2; }
		
		//XRangeValue
		public RuleCall getXfromXRangeValueParserRuleCall_2_0() { return cXfromXRangeValueParserRuleCall_2_0; }
		
		//'to'
		public Keyword getToKeyword_3() { return cToKeyword_3; }
		
		//xto=XRangeValue
		public Assignment getXtoAssignment_4() { return cXtoAssignment_4; }
		
		//XRangeValue
		public RuleCall getXtoXRangeValueParserRuleCall_4_0() { return cXtoXRangeValueParserRuleCall_4_0; }
		
		//xunits=XUnits?
		public Assignment getXunitsAssignment_5() { return cXunitsAssignment_5; }
		
		//XUnits
		public RuleCall getXunitsXUnitsParserRuleCall_5_0() { return cXunitsXUnitsParserRuleCall_5_0; }
	}
	public class XRangeValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xproject.XHDL.XRangeValue");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cXRangeValueAction_0 = (Action)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Group cGroup_1_0 = (Group)cAlternatives_1.eContents().get(0);
		private final Alternatives cAlternatives_1_0_0 = (Alternatives)cGroup_1_0.eContents().get(0);
		private final Assignment cXlvalueAssignment_1_0_0_0 = (Assignment)cAlternatives_1_0_0.eContents().get(0);
		private final RuleCall cXlvalueXLONGTerminalRuleCall_1_0_0_0_0 = (RuleCall)cXlvalueAssignment_1_0_0_0.eContents().get(0);
		private final Assignment cXdvalueAssignment_1_0_0_1 = (Assignment)cAlternatives_1_0_0.eContents().get(1);
		private final RuleCall cXdvalueXDOUBLETerminalRuleCall_1_0_0_1_0 = (RuleCall)cXdvalueAssignment_1_0_0_1.eContents().get(0);
		private final Assignment cXunitAssignment_1_0_1 = (Assignment)cGroup_1_0.eContents().get(1);
		private final RuleCall cXunitXUnitRefParserRuleCall_1_0_1_0 = (RuleCall)cXunitAssignment_1_0_1.eContents().get(0);
		private final UnorderedGroup cUnorderedGroup_1_1 = (UnorderedGroup)cAlternatives_1.eContents().get(1);
		private final Group cGroup_1_1_0 = (Group)cUnorderedGroup_1_1.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1_1_0_0 = (RuleCall)cGroup_1_1_0.eContents().get(0);
		private final Keyword cApostropheKeyword_1_1_0_1 = (Keyword)cGroup_1_1_0.eContents().get(1);
		private final RuleCall cIDTerminalRuleCall_1_1_1 = (RuleCall)cUnorderedGroup_1_1.eContents().get(1);
		
		//XRangeValue:
		//	{XRangeValue} ((xlvalue=XLONG | xdvalue=XDOUBLE) xunit=XUnitRef? | ID '\'' & ID);
		@Override public ParserRule getRule() { return rule; }
		
		//{XRangeValue} ((xlvalue=XLONG | xdvalue=XDOUBLE) xunit=XUnitRef? | ID '\'' & ID)
		public Group getGroup() { return cGroup; }
		
		//{XRangeValue}
		public Action getXRangeValueAction_0() { return cXRangeValueAction_0; }
		
		//(xlvalue=XLONG | xdvalue=XDOUBLE) xunit=XUnitRef? | ID '\'' & ID
		public Alternatives getAlternatives_1() { return cAlternatives_1; }
		
		//(xlvalue=XLONG | xdvalue=XDOUBLE) xunit=XUnitRef?
		public Group getGroup_1_0() { return cGroup_1_0; }
		
		//xlvalue=XLONG | xdvalue=XDOUBLE
		public Alternatives getAlternatives_1_0_0() { return cAlternatives_1_0_0; }
		
		//xlvalue=XLONG
		public Assignment getXlvalueAssignment_1_0_0_0() { return cXlvalueAssignment_1_0_0_0; }
		
		//XLONG
		public RuleCall getXlvalueXLONGTerminalRuleCall_1_0_0_0_0() { return cXlvalueXLONGTerminalRuleCall_1_0_0_0_0; }
		
		//xdvalue=XDOUBLE
		public Assignment getXdvalueAssignment_1_0_0_1() { return cXdvalueAssignment_1_0_0_1; }
		
		//XDOUBLE
		public RuleCall getXdvalueXDOUBLETerminalRuleCall_1_0_0_1_0() { return cXdvalueXDOUBLETerminalRuleCall_1_0_0_1_0; }
		
		//xunit=XUnitRef?
		public Assignment getXunitAssignment_1_0_1() { return cXunitAssignment_1_0_1; }
		
		//XUnitRef
		public RuleCall getXunitXUnitRefParserRuleCall_1_0_1_0() { return cXunitXUnitRefParserRuleCall_1_0_1_0; }
		
		//ID '\'' & ID
		public UnorderedGroup getUnorderedGroup_1_1() { return cUnorderedGroup_1_1; }
		
		//ID '\''
		public Group getGroup_1_1_0() { return cGroup_1_1_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1_1_0_0() { return cIDTerminalRuleCall_1_1_0_0; }
		
		//'\''
		public Keyword getApostropheKeyword_1_1_0_1() { return cApostropheKeyword_1_1_0_1; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1_1_1() { return cIDTerminalRuleCall_1_1_1; }
	}
	public class XUnitsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xproject.XHDL.XUnits");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cXUnitsAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cUnitsKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cXunitsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cXunitsXUnitParserRuleCall_2_0 = (RuleCall)cXunitsAssignment_2.eContents().get(0);
		private final Keyword cEndKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cUnitsKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//XUnits:
		//	{XUnits} 'units' xunits+=XUnit* 'end' 'units';
		@Override public ParserRule getRule() { return rule; }
		
		//{XUnits} 'units' xunits+=XUnit* 'end' 'units'
		public Group getGroup() { return cGroup; }
		
		//{XUnits}
		public Action getXUnitsAction_0() { return cXUnitsAction_0; }
		
		//'units'
		public Keyword getUnitsKeyword_1() { return cUnitsKeyword_1; }
		
		//xunits+=XUnit*
		public Assignment getXunitsAssignment_2() { return cXunitsAssignment_2; }
		
		//XUnit
		public RuleCall getXunitsXUnitParserRuleCall_2_0() { return cXunitsXUnitParserRuleCall_2_0; }
		
		//'end'
		public Keyword getEndKeyword_3() { return cEndKeyword_3; }
		
		//'units'
		public Keyword getUnitsKeyword_4() { return cUnitsKeyword_4; }
	}
	public class XUnitRefElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xproject.XHDL.XUnitRef");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cXUnitRefAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//XUnitRef:
		//	{XUnitRef} name=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//{XUnitRef} name=ID
		public Group getGroup() { return cGroup; }
		
		//{XUnitRef}
		public Action getXUnitRefAction_0() { return cXUnitRefAction_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
	}
	public class XUnitElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xproject.XHDL.XUnit");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cXUnitAction_0 = (Action)cGroup.eContents().get(0);
		private final UnorderedGroup cUnorderedGroup_1 = (UnorderedGroup)cGroup.eContents().get(1);
		private final Group cGroup_1_0 = (Group)cUnorderedGroup_1.eContents().get(0);
		private final Assignment cNameAssignment_1_0_0 = (Assignment)cGroup_1_0.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_1_0_0_0 = (RuleCall)cNameAssignment_1_0_0.eContents().get(0);
		private final UnorderedGroup cUnorderedGroup_1_0_1 = (UnorderedGroup)cGroup_1_0.eContents().get(1);
		private final Keyword cEqualsSignKeyword_1_0_1_0 = (Keyword)cUnorderedGroup_1_0_1.eContents().get(0);
		private final Group cGroup_1_0_1_1 = (Group)cUnorderedGroup_1_0_1.eContents().get(1);
		private final Assignment cXvalueAssignment_1_0_1_1_0 = (Assignment)cGroup_1_0_1_1.eContents().get(0);
		private final RuleCall cXvalueINTTerminalRuleCall_1_0_1_1_0_0 = (RuleCall)cXvalueAssignment_1_0_1_1_0.eContents().get(0);
		private final Assignment cXbasedAssignment_1_0_1_1_1 = (Assignment)cGroup_1_0_1_1.eContents().get(1);
		private final RuleCall cXbasedXUnitRefParserRuleCall_1_0_1_1_1_0 = (RuleCall)cXbasedAssignment_1_0_1_1_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_1_1 = (Keyword)cUnorderedGroup_1.eContents().get(1);
		
		//XUnit:
		//	{XUnit} (name=ID ('=' & xvalue=INT xbased=XUnitRef)? & ';');
		@Override public ParserRule getRule() { return rule; }
		
		//{XUnit} (name=ID ('=' & xvalue=INT xbased=XUnitRef)? & ';')
		public Group getGroup() { return cGroup; }
		
		//{XUnit}
		public Action getXUnitAction_0() { return cXUnitAction_0; }
		
		//name=ID ('=' & xvalue=INT xbased=XUnitRef)? & ';'
		public UnorderedGroup getUnorderedGroup_1() { return cUnorderedGroup_1; }
		
		//name=ID ('=' & xvalue=INT xbased=XUnitRef)?
		public Group getGroup_1_0() { return cGroup_1_0; }
		
		//name=ID
		public Assignment getNameAssignment_1_0_0() { return cNameAssignment_1_0_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0_0_0() { return cNameIDTerminalRuleCall_1_0_0_0; }
		
		//('=' & xvalue=INT xbased=XUnitRef)?
		public UnorderedGroup getUnorderedGroup_1_0_1() { return cUnorderedGroup_1_0_1; }
		
		//'='
		public Keyword getEqualsSignKeyword_1_0_1_0() { return cEqualsSignKeyword_1_0_1_0; }
		
		//xvalue=INT xbased=XUnitRef
		public Group getGroup_1_0_1_1() { return cGroup_1_0_1_1; }
		
		//xvalue=INT
		public Assignment getXvalueAssignment_1_0_1_1_0() { return cXvalueAssignment_1_0_1_1_0; }
		
		//INT
		public RuleCall getXvalueINTTerminalRuleCall_1_0_1_1_0_0() { return cXvalueINTTerminalRuleCall_1_0_1_1_0_0; }
		
		//xbased=XUnitRef
		public Assignment getXbasedAssignment_1_0_1_1_1() { return cXbasedAssignment_1_0_1_1_1; }
		
		//XUnitRef
		public RuleCall getXbasedXUnitRefParserRuleCall_1_0_1_1_1_0() { return cXbasedXUnitRefParserRuleCall_1_0_1_1_1_0; }
		
		//';'
		public Keyword getSemicolonKeyword_1_1() { return cSemicolonKeyword_1_1; }
	}
	public class XEnumsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xproject.XHDL.XEnums");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cXEnumsAction_0 = (Action)cGroup.eContents().get(0);
		private final UnorderedGroup cUnorderedGroup_1 = (UnorderedGroup)cGroup.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_1_0 = (Keyword)cUnorderedGroup_1.eContents().get(0);
		private final UnorderedGroup cUnorderedGroup_1_1 = (UnorderedGroup)cUnorderedGroup_1.eContents().get(1);
		private final Keyword cCommaKeyword_1_1_0 = (Keyword)cUnorderedGroup_1_1.eContents().get(0);
		private final Assignment cXenumsAssignment_1_1_1 = (Assignment)cUnorderedGroup_1_1.eContents().get(1);
		private final RuleCall cXenumsXEnumParserRuleCall_1_1_1_0 = (RuleCall)cXenumsAssignment_1_1_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_1_2 = (Keyword)cUnorderedGroup_1.eContents().get(2);
		
		//XEnums:
		//	{XEnums} ('(' & (','? & xenums+=XEnum)* & ')');
		@Override public ParserRule getRule() { return rule; }
		
		//{XEnums} ('(' & (','? & xenums+=XEnum)* & ')')
		public Group getGroup() { return cGroup; }
		
		//{XEnums}
		public Action getXEnumsAction_0() { return cXEnumsAction_0; }
		
		//'(' & (','? & xenums+=XEnum)* & ')'
		public UnorderedGroup getUnorderedGroup_1() { return cUnorderedGroup_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1_0() { return cLeftParenthesisKeyword_1_0; }
		
		//(','? & xenums+=XEnum)*
		public UnorderedGroup getUnorderedGroup_1_1() { return cUnorderedGroup_1_1; }
		
		//','?
		public Keyword getCommaKeyword_1_1_0() { return cCommaKeyword_1_1_0; }
		
		//xenums+=XEnum
		public Assignment getXenumsAssignment_1_1_1() { return cXenumsAssignment_1_1_1; }
		
		//XEnum
		public RuleCall getXenumsXEnumParserRuleCall_1_1_1_0() { return cXenumsXEnumParserRuleCall_1_1_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_1_2() { return cRightParenthesisKeyword_1_2; }
	}
	public class XFunctionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xproject.XHDL.XFunction");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cXFunctionAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cFunctionKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final UnorderedGroup cUnorderedGroup_2 = (UnorderedGroup)cGroup.eContents().get(2);
		private final Assignment cNameAssignment_2_0 = (Assignment)cUnorderedGroup_2.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_2_0_0 = (RuleCall)cNameAssignment_2_0.eContents().get(0);
		private final Assignment cXparametersAssignment_2_1 = (Assignment)cUnorderedGroup_2.eContents().get(1);
		private final RuleCall cXparametersXParametersParserRuleCall_2_1_0 = (RuleCall)cXparametersAssignment_2_1.eContents().get(0);
		private final Group cGroup_2_2 = (Group)cUnorderedGroup_2.eContents().get(2);
		private final Keyword cReturnKeyword_2_2_0 = (Keyword)cGroup_2_2.eContents().get(0);
		private final Assignment cXreturnAssignment_2_2_1 = (Assignment)cGroup_2_2.eContents().get(1);
		private final RuleCall cXreturnXTypeRefParserRuleCall_2_2_1_0 = (RuleCall)cXreturnAssignment_2_2_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_2_3 = (Keyword)cUnorderedGroup_2.eContents().get(3);
		
		//XFunction:
		//	{XFunction} 'function' (name=ID & xparameters=XParameters & 'return' xreturn=XTypeRef & ';');
		@Override public ParserRule getRule() { return rule; }
		
		//{XFunction} 'function' (name=ID & xparameters=XParameters & 'return' xreturn=XTypeRef & ';')
		public Group getGroup() { return cGroup; }
		
		//{XFunction}
		public Action getXFunctionAction_0() { return cXFunctionAction_0; }
		
		//'function'
		public Keyword getFunctionKeyword_1() { return cFunctionKeyword_1; }
		
		//name=ID & xparameters=XParameters & 'return' xreturn=XTypeRef & ';'
		public UnorderedGroup getUnorderedGroup_2() { return cUnorderedGroup_2; }
		
		//name=ID
		public Assignment getNameAssignment_2_0() { return cNameAssignment_2_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0_0() { return cNameIDTerminalRuleCall_2_0_0; }
		
		//xparameters=XParameters
		public Assignment getXparametersAssignment_2_1() { return cXparametersAssignment_2_1; }
		
		//XParameters
		public RuleCall getXparametersXParametersParserRuleCall_2_1_0() { return cXparametersXParametersParserRuleCall_2_1_0; }
		
		//'return' xreturn=XTypeRef
		public Group getGroup_2_2() { return cGroup_2_2; }
		
		//'return'
		public Keyword getReturnKeyword_2_2_0() { return cReturnKeyword_2_2_0; }
		
		//xreturn=XTypeRef
		public Assignment getXreturnAssignment_2_2_1() { return cXreturnAssignment_2_2_1; }
		
		//XTypeRef
		public RuleCall getXreturnXTypeRefParserRuleCall_2_2_1_0() { return cXreturnXTypeRefParserRuleCall_2_2_1_0; }
		
		//';'
		public Keyword getSemicolonKeyword_2_3() { return cSemicolonKeyword_2_3; }
	}
	public class XImpureElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xproject.XHDL.XImpure");
		private final UnorderedGroup cUnorderedGroup = (UnorderedGroup)rule.eContents().get(1);
		private final Keyword cImpureKeyword_0 = (Keyword)cUnorderedGroup.eContents().get(0);
		private final Assignment cXfuncAssignment_1 = (Assignment)cUnorderedGroup.eContents().get(1);
		private final RuleCall cXfuncXFunctionParserRuleCall_1_0 = (RuleCall)cXfuncAssignment_1.eContents().get(0);
		
		//XImpure:
		//	'impure' & xfunc=XFunction;
		@Override public ParserRule getRule() { return rule; }
		
		//'impure' & xfunc=XFunction
		public UnorderedGroup getUnorderedGroup() { return cUnorderedGroup; }
		
		//'impure'
		public Keyword getImpureKeyword_0() { return cImpureKeyword_0; }
		
		//xfunc=XFunction
		public Assignment getXfuncAssignment_1() { return cXfuncAssignment_1; }
		
		//XFunction
		public RuleCall getXfuncXFunctionParserRuleCall_1_0() { return cXfuncXFunctionParserRuleCall_1_0; }
	}
	public class XEnumElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xproject.XHDL.XEnum");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//XEnum:
		//	name=ID | name=STRING;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID | name=STRING
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }
		
		//name=STRING
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_0() { return cNameSTRINGTerminalRuleCall_1_0; }
	}
	public class XAccessElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xproject.XHDL.XAccess");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cXAccessAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cAccessKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cXtypeAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cXtypeXTypeRefParserRuleCall_2_0 = (RuleCall)cXtypeAssignment_2.eContents().get(0);
		
		//XAccess:
		//	{XAccess} 'access' xtype=XTypeRef;
		@Override public ParserRule getRule() { return rule; }
		
		//{XAccess} 'access' xtype=XTypeRef
		public Group getGroup() { return cGroup; }
		
		//{XAccess}
		public Action getXAccessAction_0() { return cXAccessAction_0; }
		
		//'access'
		public Keyword getAccessKeyword_1() { return cAccessKeyword_1; }
		
		//xtype=XTypeRef
		public Assignment getXtypeAssignment_2() { return cXtypeAssignment_2; }
		
		//XTypeRef
		public RuleCall getXtypeXTypeRefParserRuleCall_2_0() { return cXtypeXTypeRefParserRuleCall_2_0; }
	}
	public class XFileOfElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xproject.XHDL.XFileOf");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cXFileAction_0 = (Action)cGroup.eContents().get(0);
		private final UnorderedGroup cUnorderedGroup_1 = (UnorderedGroup)cGroup.eContents().get(1);
		private final Keyword cFileKeyword_1_0 = (Keyword)cUnorderedGroup_1.eContents().get(0);
		private final Group cGroup_1_1 = (Group)cUnorderedGroup_1.eContents().get(1);
		private final Keyword cOfKeyword_1_1_0 = (Keyword)cGroup_1_1.eContents().get(0);
		private final Assignment cXtypeAssignment_1_1_1 = (Assignment)cGroup_1_1.eContents().get(1);
		private final RuleCall cXtypeXTypeRefParserRuleCall_1_1_1_0 = (RuleCall)cXtypeAssignment_1_1_1.eContents().get(0);
		
		//XFileOf:
		//	{XFile} ('file' & 'of' xtype=XTypeRef);
		@Override public ParserRule getRule() { return rule; }
		
		//{XFile} ('file' & 'of' xtype=XTypeRef)
		public Group getGroup() { return cGroup; }
		
		//{XFile}
		public Action getXFileAction_0() { return cXFileAction_0; }
		
		//'file' & 'of' xtype=XTypeRef
		public UnorderedGroup getUnorderedGroup_1() { return cUnorderedGroup_1; }
		
		//'file'
		public Keyword getFileKeyword_1_0() { return cFileKeyword_1_0; }
		
		//'of' xtype=XTypeRef
		public Group getGroup_1_1() { return cGroup_1_1; }
		
		//'of'
		public Keyword getOfKeyword_1_1_0() { return cOfKeyword_1_1_0; }
		
		//xtype=XTypeRef
		public Assignment getXtypeAssignment_1_1_1() { return cXtypeAssignment_1_1_1; }
		
		//XTypeRef
		public RuleCall getXtypeXTypeRefParserRuleCall_1_1_1_0() { return cXtypeXTypeRefParserRuleCall_1_1_1_0; }
	}
	public class XParameterElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xproject.XHDL.XParameter");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cXParameterAction_0 = (Action)cGroup.eContents().get(0);
		private final UnorderedGroup cUnorderedGroup_1 = (UnorderedGroup)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_1_0 = (Assignment)cUnorderedGroup_1.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_1_0_0 = (RuleCall)cNameAssignment_1_0.eContents().get(0);
		private final Keyword cColonKeyword_1_1 = (Keyword)cUnorderedGroup_1.eContents().get(1);
		private final Assignment cXtypeAssignment_1_2 = (Assignment)cUnorderedGroup_1.eContents().get(2);
		private final RuleCall cXtypeXTypeRefParserRuleCall_1_2_0 = (RuleCall)cXtypeAssignment_1_2.eContents().get(0);
		private final UnorderedGroup cUnorderedGroup_1_3 = (UnorderedGroup)cUnorderedGroup_1.eContents().get(3);
		private final Keyword cColonEqualsSignKeyword_1_3_0 = (Keyword)cUnorderedGroup_1_3.eContents().get(0);
		private final Assignment cXdefaultValueAssignment_1_3_1 = (Assignment)cUnorderedGroup_1_3.eContents().get(1);
		private final RuleCall cXdefaultValueIDTerminalRuleCall_1_3_1_0 = (RuleCall)cXdefaultValueAssignment_1_3_1.eContents().get(0);
		
		//XParameter:
		//	{XParameter} (name=ID & ':' & xtype=XTypeRef & (':=' & xdefaultValue=ID)?);
		@Override public ParserRule getRule() { return rule; }
		
		//{XParameter} (name=ID & ':' & xtype=XTypeRef & (':=' & xdefaultValue=ID)?)
		public Group getGroup() { return cGroup; }
		
		//{XParameter}
		public Action getXParameterAction_0() { return cXParameterAction_0; }
		
		//name=ID & ':' & xtype=XTypeRef & (':=' & xdefaultValue=ID)?
		public UnorderedGroup getUnorderedGroup_1() { return cUnorderedGroup_1; }
		
		//name=ID
		public Assignment getNameAssignment_1_0() { return cNameAssignment_1_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0_0() { return cNameIDTerminalRuleCall_1_0_0; }
		
		//':'
		public Keyword getColonKeyword_1_1() { return cColonKeyword_1_1; }
		
		//xtype=XTypeRef
		public Assignment getXtypeAssignment_1_2() { return cXtypeAssignment_1_2; }
		
		//XTypeRef
		public RuleCall getXtypeXTypeRefParserRuleCall_1_2_0() { return cXtypeXTypeRefParserRuleCall_1_2_0; }
		
		//(':=' & xdefaultValue=ID)?
		public UnorderedGroup getUnorderedGroup_1_3() { return cUnorderedGroup_1_3; }
		
		//':='
		public Keyword getColonEqualsSignKeyword_1_3_0() { return cColonEqualsSignKeyword_1_3_0; }
		
		//xdefaultValue=ID
		public Assignment getXdefaultValueAssignment_1_3_1() { return cXdefaultValueAssignment_1_3_1; }
		
		//ID
		public RuleCall getXdefaultValueIDTerminalRuleCall_1_3_1_0() { return cXdefaultValueIDTerminalRuleCall_1_3_1_0; }
	}
	public class XProcedureElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xproject.XHDL.XProcedure");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cXProcedureAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cProcedureKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final UnorderedGroup cUnorderedGroup_2 = (UnorderedGroup)cGroup.eContents().get(2);
		private final Assignment cNameAssignment_2_0 = (Assignment)cUnorderedGroup_2.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_2_0_0 = (RuleCall)cNameAssignment_2_0.eContents().get(0);
		private final Assignment cXinputsAssignment_2_1 = (Assignment)cUnorderedGroup_2.eContents().get(1);
		private final RuleCall cXinputsXInputsParserRuleCall_2_1_0 = (RuleCall)cXinputsAssignment_2_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_2_2 = (Keyword)cUnorderedGroup_2.eContents().get(2);
		
		//XProcedure:
		//	{XProcedure} 'procedure' (name=ID & xinputs=XInputs & ';');
		@Override public ParserRule getRule() { return rule; }
		
		//{XProcedure} 'procedure' (name=ID & xinputs=XInputs & ';')
		public Group getGroup() { return cGroup; }
		
		//{XProcedure}
		public Action getXProcedureAction_0() { return cXProcedureAction_0; }
		
		//'procedure'
		public Keyword getProcedureKeyword_1() { return cProcedureKeyword_1; }
		
		//name=ID & xinputs=XInputs & ';'
		public UnorderedGroup getUnorderedGroup_2() { return cUnorderedGroup_2; }
		
		//name=ID
		public Assignment getNameAssignment_2_0() { return cNameAssignment_2_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0_0() { return cNameIDTerminalRuleCall_2_0_0; }
		
		//xinputs=XInputs
		public Assignment getXinputsAssignment_2_1() { return cXinputsAssignment_2_1; }
		
		//XInputs
		public RuleCall getXinputsXInputsParserRuleCall_2_1_0() { return cXinputsXInputsParserRuleCall_2_1_0; }
		
		//';'
		public Keyword getSemicolonKeyword_2_2() { return cSemicolonKeyword_2_2; }
	}
	public class XInputElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xproject.XHDL.XInput");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Action cXInputAction_0_0 = (Action)cGroup_0.eContents().get(0);
		private final UnorderedGroup cUnorderedGroup_0_1 = (UnorderedGroup)cGroup_0.eContents().get(1);
		private final Assignment cNameAssignment_0_1_0 = (Assignment)cUnorderedGroup_0_1.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_1_0_0 = (RuleCall)cNameAssignment_0_1_0.eContents().get(0);
		private final Keyword cColonKeyword_0_1_1 = (Keyword)cUnorderedGroup_0_1.eContents().get(1);
		private final Group cGroup_0_1_2 = (Group)cUnorderedGroup_0_1.eContents().get(2);
		private final Alternatives cAlternatives_0_1_2_0 = (Alternatives)cGroup_0_1_2.eContents().get(0);
		private final Assignment cXinoutAssignment_0_1_2_0_0 = (Assignment)cAlternatives_0_1_2_0.eContents().get(0);
		private final Keyword cXinoutInKeyword_0_1_2_0_0_0 = (Keyword)cXinoutAssignment_0_1_2_0_0.eContents().get(0);
		private final Assignment cXinoutAssignment_0_1_2_0_1 = (Assignment)cAlternatives_0_1_2_0.eContents().get(1);
		private final Keyword cXinoutInoutKeyword_0_1_2_0_1_0 = (Keyword)cXinoutAssignment_0_1_2_0_1.eContents().get(0);
		private final Assignment cXinoutAssignment_0_1_2_0_2 = (Assignment)cAlternatives_0_1_2_0.eContents().get(2);
		private final Keyword cXinoutOutKeyword_0_1_2_0_2_0 = (Keyword)cXinoutAssignment_0_1_2_0_2.eContents().get(0);
		private final Assignment cXtypAssignment_0_1_2_1 = (Assignment)cGroup_0_1_2.eContents().get(1);
		private final RuleCall cXtypXTypeRefParserRuleCall_0_1_2_1_0 = (RuleCall)cXtypAssignment_0_1_2_1.eContents().get(0);
		private final RuleCall cXFileRefParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//XInput:
		//	{XInput} (name=ID & ':' & (xinout='in' | xinout='inout' | xinout='out')? xtyp=XTypeRef) | XFileRef;
		@Override public ParserRule getRule() { return rule; }
		
		//{XInput} (name=ID & ':' & (xinout='in' | xinout='inout' | xinout='out')? xtyp=XTypeRef) | XFileRef
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//{XInput} (name=ID & ':' & (xinout='in' | xinout='inout' | xinout='out')? xtyp=XTypeRef)
		public Group getGroup_0() { return cGroup_0; }
		
		//{XInput}
		public Action getXInputAction_0_0() { return cXInputAction_0_0; }
		
		//name=ID & ':' & (xinout='in' | xinout='inout' | xinout='out')? xtyp=XTypeRef
		public UnorderedGroup getUnorderedGroup_0_1() { return cUnorderedGroup_0_1; }
		
		//name=ID
		public Assignment getNameAssignment_0_1_0() { return cNameAssignment_0_1_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0_1_0_0() { return cNameIDTerminalRuleCall_0_1_0_0; }
		
		//':'
		public Keyword getColonKeyword_0_1_1() { return cColonKeyword_0_1_1; }
		
		//(xinout='in' | xinout='inout' | xinout='out')? xtyp=XTypeRef
		public Group getGroup_0_1_2() { return cGroup_0_1_2; }
		
		//(xinout='in' | xinout='inout' | xinout='out')?
		public Alternatives getAlternatives_0_1_2_0() { return cAlternatives_0_1_2_0; }
		
		//xinout='in'
		public Assignment getXinoutAssignment_0_1_2_0_0() { return cXinoutAssignment_0_1_2_0_0; }
		
		//'in'
		public Keyword getXinoutInKeyword_0_1_2_0_0_0() { return cXinoutInKeyword_0_1_2_0_0_0; }
		
		//xinout='inout'
		public Assignment getXinoutAssignment_0_1_2_0_1() { return cXinoutAssignment_0_1_2_0_1; }
		
		//'inout'
		public Keyword getXinoutInoutKeyword_0_1_2_0_1_0() { return cXinoutInoutKeyword_0_1_2_0_1_0; }
		
		//xinout='out'
		public Assignment getXinoutAssignment_0_1_2_0_2() { return cXinoutAssignment_0_1_2_0_2; }
		
		//'out'
		public Keyword getXinoutOutKeyword_0_1_2_0_2_0() { return cXinoutOutKeyword_0_1_2_0_2_0; }
		
		//xtyp=XTypeRef
		public Assignment getXtypAssignment_0_1_2_1() { return cXtypAssignment_0_1_2_1; }
		
		//XTypeRef
		public RuleCall getXtypXTypeRefParserRuleCall_0_1_2_1_0() { return cXtypXTypeRefParserRuleCall_0_1_2_1_0; }
		
		//XFileRef
		public RuleCall getXFileRefParserRuleCall_1() { return cXFileRefParserRuleCall_1; }
	}
	public class XFileRefElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xproject.XHDL.XFileRef");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cXFileRefAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cFileKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final UnorderedGroup cUnorderedGroup_2 = (UnorderedGroup)cGroup.eContents().get(2);
		private final Assignment cNameAssignment_2_0 = (Assignment)cUnorderedGroup_2.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_2_0_0 = (RuleCall)cNameAssignment_2_0.eContents().get(0);
		private final Keyword cColonKeyword_2_1 = (Keyword)cUnorderedGroup_2.eContents().get(1);
		private final Assignment cXtypeAssignment_2_2 = (Assignment)cUnorderedGroup_2.eContents().get(2);
		private final RuleCall cXtypeXTypeRefParserRuleCall_2_2_0 = (RuleCall)cXtypeAssignment_2_2.eContents().get(0);
		
		//XFileRef:
		//	{XFileRef} 'file' (name=ID & ':' & xtype=XTypeRef);
		@Override public ParserRule getRule() { return rule; }
		
		//{XFileRef} 'file' (name=ID & ':' & xtype=XTypeRef)
		public Group getGroup() { return cGroup; }
		
		//{XFileRef}
		public Action getXFileRefAction_0() { return cXFileRefAction_0; }
		
		//'file'
		public Keyword getFileKeyword_1() { return cFileKeyword_1; }
		
		//name=ID & ':' & xtype=XTypeRef
		public UnorderedGroup getUnorderedGroup_2() { return cUnorderedGroup_2; }
		
		//name=ID
		public Assignment getNameAssignment_2_0() { return cNameAssignment_2_0; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_2_0_0() { return cNameIDTerminalRuleCall_2_0_0; }
		
		//':'
		public Keyword getColonKeyword_2_1() { return cColonKeyword_2_1; }
		
		//xtype=XTypeRef
		public Assignment getXtypeAssignment_2_2() { return cXtypeAssignment_2_2; }
		
		//XTypeRef
		public RuleCall getXtypeXTypeRefParserRuleCall_2_2_0() { return cXtypeXTypeRefParserRuleCall_2_2_0; }
	}
	public class XInputsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xproject.XHDL.XInputs");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cXInputsAction_0 = (Action)cGroup.eContents().get(0);
		private final UnorderedGroup cUnorderedGroup_1 = (UnorderedGroup)cGroup.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_1_0 = (Keyword)cUnorderedGroup_1.eContents().get(0);
		private final UnorderedGroup cUnorderedGroup_1_1 = (UnorderedGroup)cUnorderedGroup_1.eContents().get(1);
		private final Keyword cSemicolonKeyword_1_1_0 = (Keyword)cUnorderedGroup_1_1.eContents().get(0);
		private final Assignment cXinputsAssignment_1_1_1 = (Assignment)cUnorderedGroup_1_1.eContents().get(1);
		private final RuleCall cXinputsXInputParserRuleCall_1_1_1_0 = (RuleCall)cXinputsAssignment_1_1_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_1_2 = (Keyword)cUnorderedGroup_1.eContents().get(2);
		
		//XInputs:
		//	{XInputs} ('(' & (';'? & xinputs+=XInput)* & ')');
		@Override public ParserRule getRule() { return rule; }
		
		//{XInputs} ('(' & (';'? & xinputs+=XInput)* & ')')
		public Group getGroup() { return cGroup; }
		
		//{XInputs}
		public Action getXInputsAction_0() { return cXInputsAction_0; }
		
		//'(' & (';'? & xinputs+=XInput)* & ')'
		public UnorderedGroup getUnorderedGroup_1() { return cUnorderedGroup_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1_0() { return cLeftParenthesisKeyword_1_0; }
		
		//(';'? & xinputs+=XInput)*
		public UnorderedGroup getUnorderedGroup_1_1() { return cUnorderedGroup_1_1; }
		
		//';'?
		public Keyword getSemicolonKeyword_1_1_0() { return cSemicolonKeyword_1_1_0; }
		
		//xinputs+=XInput
		public Assignment getXinputsAssignment_1_1_1() { return cXinputsAssignment_1_1_1; }
		
		//XInput
		public RuleCall getXinputsXInputParserRuleCall_1_1_1_0() { return cXinputsXInputParserRuleCall_1_1_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_1_2() { return cRightParenthesisKeyword_1_2; }
	}
	public class XParametersElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "xproject.XHDL.XParameters");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cXParametersAction_0 = (Action)cGroup.eContents().get(0);
		private final UnorderedGroup cUnorderedGroup_1 = (UnorderedGroup)cGroup.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_1_0 = (Keyword)cUnorderedGroup_1.eContents().get(0);
		private final UnorderedGroup cUnorderedGroup_1_1 = (UnorderedGroup)cUnorderedGroup_1.eContents().get(1);
		private final Keyword cSemicolonKeyword_1_1_0 = (Keyword)cUnorderedGroup_1_1.eContents().get(0);
		private final Assignment cXparametersAssignment_1_1_1 = (Assignment)cUnorderedGroup_1_1.eContents().get(1);
		private final RuleCall cXparametersXParameterParserRuleCall_1_1_1_0 = (RuleCall)cXparametersAssignment_1_1_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_1_2 = (Keyword)cUnorderedGroup_1.eContents().get(2);
		
		//XParameters:
		//	{XParameters} ('(' & (';'? & xparameters+=XParameter)* & ')');
		@Override public ParserRule getRule() { return rule; }
		
		//{XParameters} ('(' & (';'? & xparameters+=XParameter)* & ')')
		public Group getGroup() { return cGroup; }
		
		//{XParameters}
		public Action getXParametersAction_0() { return cXParametersAction_0; }
		
		//'(' & (';'? & xparameters+=XParameter)* & ')'
		public UnorderedGroup getUnorderedGroup_1() { return cUnorderedGroup_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1_0() { return cLeftParenthesisKeyword_1_0; }
		
		//(';'? & xparameters+=XParameter)*
		public UnorderedGroup getUnorderedGroup_1_1() { return cUnorderedGroup_1_1; }
		
		//';'?
		public Keyword getSemicolonKeyword_1_1_0() { return cSemicolonKeyword_1_1_0; }
		
		//xparameters+=XParameter
		public Assignment getXparametersAssignment_1_1_1() { return cXparametersAssignment_1_1_1; }
		
		//XParameter
		public RuleCall getXparametersXParameterParserRuleCall_1_1_1_0() { return cXparametersXParameterParserRuleCall_1_1_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_1_2() { return cRightParenthesisKeyword_1_2; }
	}
	
	
	private final XhdlElements pXhdl;
	private final TerminalRule tCOMMENT;
	private final TerminalRule tXLONG;
	private final TerminalRule tXDOUBLE;
	private final XPackageRefElements pXPackageRef;
	private final XPackageElements pXPackage;
	private final XTypeRefElements pXTypeRef;
	private final XElementElements pXElement;
	private final XAttributeElements pXAttribute;
	private final XSubTypeElements pXSubType;
	private final XSignalElements pXSignal;
	private final XTypeElements pXType;
	private final XArrayElements pXArray;
	private final XRangeElements pXRange;
	private final XRangeValueElements pXRangeValue;
	private final XUnitsElements pXUnits;
	private final XUnitRefElements pXUnitRef;
	private final XUnitElements pXUnit;
	private final XEnumsElements pXEnums;
	private final XFunctionElements pXFunction;
	private final XImpureElements pXImpure;
	private final XEnumElements pXEnum;
	private final XAccessElements pXAccess;
	private final XFileOfElements pXFileOf;
	private final XParameterElements pXParameter;
	private final XProcedureElements pXProcedure;
	private final XInputElements pXInput;
	private final XFileRefElements pXFileRef;
	private final XInputsElements pXInputs;
	private final XParametersElements pXParameters;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public XHDLGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pXhdl = new XhdlElements();
		this.tCOMMENT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "xproject.XHDL.COMMENT");
		this.tXLONG = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "xproject.XHDL.XLONG");
		this.tXDOUBLE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "xproject.XHDL.XDOUBLE");
		this.pXPackageRef = new XPackageRefElements();
		this.pXPackage = new XPackageElements();
		this.pXTypeRef = new XTypeRefElements();
		this.pXElement = new XElementElements();
		this.pXAttribute = new XAttributeElements();
		this.pXSubType = new XSubTypeElements();
		this.pXSignal = new XSignalElements();
		this.pXType = new XTypeElements();
		this.pXArray = new XArrayElements();
		this.pXRange = new XRangeElements();
		this.pXRangeValue = new XRangeValueElements();
		this.pXUnits = new XUnitsElements();
		this.pXUnitRef = new XUnitRefElements();
		this.pXUnit = new XUnitElements();
		this.pXEnums = new XEnumsElements();
		this.pXFunction = new XFunctionElements();
		this.pXImpure = new XImpureElements();
		this.pXEnum = new XEnumElements();
		this.pXAccess = new XAccessElements();
		this.pXFileOf = new XFileOfElements();
		this.pXParameter = new XParameterElements();
		this.pXProcedure = new XProcedureElements();
		this.pXInput = new XInputElements();
		this.pXFileRef = new XFileRefElements();
		this.pXInputs = new XInputsElements();
		this.pXParameters = new XParametersElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("xproject.XHDL".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//xhdl:
	//	packages+=XPackage*;
	public XhdlElements getXhdlAccess() {
		return pXhdl;
	}
	
	public ParserRule getXhdlRule() {
		return getXhdlAccess().getRule();
	}
	
	//terminal COMMENT:
	//	'--' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getCOMMENTRule() {
		return tCOMMENT;
	}
	
	//terminal XLONG returns ecore::ELong:
	//	'-'? '0'..'9'+;
	public TerminalRule getXLONGRule() {
		return tXLONG;
	}
	
	//terminal XDOUBLE returns ecore::EDouble:
	//	'[-+]?[0-9]*\\.?[0-9]+([eE][-+]?[0-9]+)?';
	public TerminalRule getXDOUBLERule() {
		return tXDOUBLE;
	}
	
	//XPackageRef:
	//	{XPackageRef} name=ID;
	public XPackageRefElements getXPackageRefAccess() {
		return pXPackageRef;
	}
	
	public ParserRule getXPackageRefRule() {
		return getXPackageRefAccess().getRule();
	}
	
	//XPackage:
	//	'package' name=ID 'is'
	//	xis+=XElement*
	//	'end' (xend=XPackageRef & ';');
	public XPackageElements getXPackageAccess() {
		return pXPackage;
	}
	
	public ParserRule getXPackageRule() {
		return getXPackageAccess().getRule();
	}
	
	//XTypeRef:
	//	{XTypeRef} name=ID;
	public XTypeRefElements getXTypeRefAccess() {
		return pXTypeRef;
	}
	
	public ParserRule getXTypeRefRule() {
		return getXTypeRefAccess().getRule();
	}
	
	//XElement:
	//	XType | XSignal | XSubType | XAttribute | XImpure | XFunction | XProcedure;
	public XElementElements getXElementAccess() {
		return pXElement;
	}
	
	public ParserRule getXElementRule() {
		return getXElementAccess().getRule();
	}
	
	//XAttribute:
	//	{XAttribute} 'attribute' (name=ID & ':' & xtype=XTypeRef & ';');
	public XAttributeElements getXAttributeAccess() {
		return pXAttribute;
	}
	
	public ParserRule getXAttributeRule() {
		return getXAttributeAccess().getRule();
	}
	
	//XSubType:
	//	{XSubType} 'subtype' name=ID 'is' (xis=XTypeRef xrange=XRange? & ';');
	public XSubTypeElements getXSubTypeAccess() {
		return pXSubType;
	}
	
	public ParserRule getXSubTypeRule() {
		return getXSubTypeAccess().getRule();
	}
	
	//XSignal:
	//	{XSignal} 'signal' (name=ID & ':' xtype=XTypeRef & (';=' & ID)? & ';');
	public XSignalElements getXSignalAccess() {
		return pXSignal;
	}
	
	public ParserRule getXSignalRule() {
		return getXSignalAccess().getRule();
	}
	
	//XType:
	//	{XType} 'type' name=ID 'is' ((xenums=XEnums | xrange=XRange | xarray=XArray | xaccess=XAccess | xfileOf=XFileOf) &
	//	';');
	public XTypeElements getXTypeAccess() {
		return pXType;
	}
	
	public ParserRule getXTypeRule() {
		return getXTypeAccess().getRule();
	}
	
	//XArray:
	//	{XArray} 'array' ('(' & xrange=XTypeRef 'range' '<>' & ')') 'of' xof=XTypeRef;
	public XArrayElements getXArrayAccess() {
		return pXArray;
	}
	
	public ParserRule getXArrayRule() {
		return getXArrayAccess().getRule();
	}
	
	//XRange:
	//	{XRange} 'range' xfrom=XRangeValue 'to' xto=XRangeValue xunits=XUnits?;
	public XRangeElements getXRangeAccess() {
		return pXRange;
	}
	
	public ParserRule getXRangeRule() {
		return getXRangeAccess().getRule();
	}
	
	//XRangeValue:
	//	{XRangeValue} ((xlvalue=XLONG | xdvalue=XDOUBLE) xunit=XUnitRef? | ID '\'' & ID);
	public XRangeValueElements getXRangeValueAccess() {
		return pXRangeValue;
	}
	
	public ParserRule getXRangeValueRule() {
		return getXRangeValueAccess().getRule();
	}
	
	//XUnits:
	//	{XUnits} 'units' xunits+=XUnit* 'end' 'units';
	public XUnitsElements getXUnitsAccess() {
		return pXUnits;
	}
	
	public ParserRule getXUnitsRule() {
		return getXUnitsAccess().getRule();
	}
	
	//XUnitRef:
	//	{XUnitRef} name=ID;
	public XUnitRefElements getXUnitRefAccess() {
		return pXUnitRef;
	}
	
	public ParserRule getXUnitRefRule() {
		return getXUnitRefAccess().getRule();
	}
	
	//XUnit:
	//	{XUnit} (name=ID ('=' & xvalue=INT xbased=XUnitRef)? & ';');
	public XUnitElements getXUnitAccess() {
		return pXUnit;
	}
	
	public ParserRule getXUnitRule() {
		return getXUnitAccess().getRule();
	}
	
	//XEnums:
	//	{XEnums} ('(' & (','? & xenums+=XEnum)* & ')');
	public XEnumsElements getXEnumsAccess() {
		return pXEnums;
	}
	
	public ParserRule getXEnumsRule() {
		return getXEnumsAccess().getRule();
	}
	
	//XFunction:
	//	{XFunction} 'function' (name=ID & xparameters=XParameters & 'return' xreturn=XTypeRef & ';');
	public XFunctionElements getXFunctionAccess() {
		return pXFunction;
	}
	
	public ParserRule getXFunctionRule() {
		return getXFunctionAccess().getRule();
	}
	
	//XImpure:
	//	'impure' & xfunc=XFunction;
	public XImpureElements getXImpureAccess() {
		return pXImpure;
	}
	
	public ParserRule getXImpureRule() {
		return getXImpureAccess().getRule();
	}
	
	//XEnum:
	//	name=ID | name=STRING;
	public XEnumElements getXEnumAccess() {
		return pXEnum;
	}
	
	public ParserRule getXEnumRule() {
		return getXEnumAccess().getRule();
	}
	
	//XAccess:
	//	{XAccess} 'access' xtype=XTypeRef;
	public XAccessElements getXAccessAccess() {
		return pXAccess;
	}
	
	public ParserRule getXAccessRule() {
		return getXAccessAccess().getRule();
	}
	
	//XFileOf:
	//	{XFile} ('file' & 'of' xtype=XTypeRef);
	public XFileOfElements getXFileOfAccess() {
		return pXFileOf;
	}
	
	public ParserRule getXFileOfRule() {
		return getXFileOfAccess().getRule();
	}
	
	//XParameter:
	//	{XParameter} (name=ID & ':' & xtype=XTypeRef & (':=' & xdefaultValue=ID)?);
	public XParameterElements getXParameterAccess() {
		return pXParameter;
	}
	
	public ParserRule getXParameterRule() {
		return getXParameterAccess().getRule();
	}
	
	//XProcedure:
	//	{XProcedure} 'procedure' (name=ID & xinputs=XInputs & ';');
	public XProcedureElements getXProcedureAccess() {
		return pXProcedure;
	}
	
	public ParserRule getXProcedureRule() {
		return getXProcedureAccess().getRule();
	}
	
	//XInput:
	//	{XInput} (name=ID & ':' & (xinout='in' | xinout='inout' | xinout='out')? xtyp=XTypeRef) | XFileRef;
	public XInputElements getXInputAccess() {
		return pXInput;
	}
	
	public ParserRule getXInputRule() {
		return getXInputAccess().getRule();
	}
	
	//XFileRef:
	//	{XFileRef} 'file' (name=ID & ':' & xtype=XTypeRef);
	public XFileRefElements getXFileRefAccess() {
		return pXFileRef;
	}
	
	public ParserRule getXFileRefRule() {
		return getXFileRefAccess().getRule();
	}
	
	//XInputs:
	//	{XInputs} ('(' & (';'? & xinputs+=XInput)* & ')');
	public XInputsElements getXInputsAccess() {
		return pXInputs;
	}
	
	public ParserRule getXInputsRule() {
		return getXInputsAccess().getRule();
	}
	
	//XParameters:
	//	{XParameters} ('(' & (';'? & xparameters+=XParameter)* & ')');
	public XParametersElements getXParametersAccess() {
		return pXParameters;
	}
	
	public ParserRule getXParametersRule() {
		return getXParametersAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
