/**
 * generated by Xtext 2.15.0
 */
package xproject.xhdl.impl;

import org.eclipse.emf.ecore.EClass;

import xproject.xhdl.XhdlPackage;
import xproject.xhdl.array;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>array</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class arrayImpl extends XArrayImpl implements array
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected arrayImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return XhdlPackage.Literals.ARRAY;
  }

} //arrayImpl
