/**
 * generated by Xtext 2.15.0
 */
package xproject.xhdl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>subtype</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see xproject.xhdl.XhdlPackage#getsubtype()
 * @model
 * @generated
 */
public interface subtype extends XSubType
{
} // subtype
