/**
 * generated by Xtext 2.15.0
 */
package xproject.xhdl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>XAttribute</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xproject.xhdl.XAttribute#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see xproject.xhdl.XhdlPackage#getXAttribute()
 * @model
 * @generated
 */
public interface XAttribute extends XElement
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' reference.
   * @see #setType(XType)
   * @see xproject.xhdl.XhdlPackage#getXAttribute_Type()
   * @model
   * @generated
   */
  XType getType();

  /**
   * Sets the value of the '{@link xproject.xhdl.XAttribute#getType <em>Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' reference.
   * @see #getType()
   * @generated
   */
  void setType(XType value);

} // XAttribute
