/**
 * generated by Xtext 2.15.0
 */
package xproject.xhdl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>XElement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see xproject.xhdl.XhdlPackage#getXElement()
 * @model
 * @generated
 */
public interface XElement extends EObject
{
} // XElement
