/**
 * generated by Xtext 2.15.0
 */
package xproject.xhdl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>XEnums</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xproject.xhdl.XEnums#getXenums <em>Xenums</em>}</li>
 * </ul>
 *
 * @see xproject.xhdl.XhdlPackage#getXEnums()
 * @model
 * @generated
 */
public interface XEnums extends EObject
{
  /**
   * Returns the value of the '<em><b>Xenums</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Xenums</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Xenums</em>' attribute list.
   * @see xproject.xhdl.XhdlPackage#getXEnums_Xenums()
   * @model unique="false"
   * @generated
   */
  EList<String> getXenums();

} // XEnums
