/**
 * generated by Xtext 2.15.0
 */
package xproject.xhdl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see xproject.xhdl.XhdlFactory
 * @model kind="package"
 * @generated
 */
public interface XhdlPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "xhdl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xproject.org/xhdl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "xhdl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  XhdlPackage eINSTANCE = xproject.xhdl.impl.XhdlPackageImpl.init();

  /**
   * The meta object id for the '{@link xproject.xhdl.impl.xhdlImpl <em>xhdl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xproject.xhdl.impl.xhdlImpl
   * @see xproject.xhdl.impl.XhdlPackageImpl#getxhdl()
   * @generated
   */
  int XHDL = 0;

  /**
   * The feature id for the '<em><b>Packages</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XHDL__PACKAGES = 0;

  /**
   * The number of structural features of the '<em>xhdl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XHDL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link xproject.xhdl.impl.XPackageImpl <em>XPackage</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xproject.xhdl.impl.XPackageImpl
   * @see xproject.xhdl.impl.XhdlPackageImpl#getXPackage()
   * @generated
   */
  int XPACKAGE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XPACKAGE__NAME = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XPACKAGE__ELEMENTS = 1;

  /**
   * The number of structural features of the '<em>XPackage</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XPACKAGE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link xproject.xhdl.impl.XElementImpl <em>XElement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xproject.xhdl.impl.XElementImpl
   * @see xproject.xhdl.impl.XhdlPackageImpl#getXElement()
   * @generated
   */
  int XELEMENT = 2;

  /**
   * The number of structural features of the '<em>XElement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XELEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link xproject.xhdl.impl.XAttributeImpl <em>XAttribute</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xproject.xhdl.impl.XAttributeImpl
   * @see xproject.xhdl.impl.XhdlPackageImpl#getXAttribute()
   * @generated
   */
  int XATTRIBUTE = 3;

  /**
   * The number of structural features of the '<em>XAttribute</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XATTRIBUTE_FEATURE_COUNT = XELEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link xproject.xhdl.impl.XSubTypeImpl <em>XSub Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xproject.xhdl.impl.XSubTypeImpl
   * @see xproject.xhdl.impl.XhdlPackageImpl#getXSubType()
   * @generated
   */
  int XSUB_TYPE = 4;

  /**
   * The number of structural features of the '<em>XSub Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XSUB_TYPE_FEATURE_COUNT = XELEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link xproject.xhdl.impl.XSignalImpl <em>XSignal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xproject.xhdl.impl.XSignalImpl
   * @see xproject.xhdl.impl.XhdlPackageImpl#getXSignal()
   * @generated
   */
  int XSIGNAL = 5;

  /**
   * The number of structural features of the '<em>XSignal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XSIGNAL_FEATURE_COUNT = XELEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link xproject.xhdl.impl.XTypeImpl <em>XType</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xproject.xhdl.impl.XTypeImpl
   * @see xproject.xhdl.impl.XhdlPackageImpl#getXType()
   * @generated
   */
  int XTYPE = 6;

  /**
   * The number of structural features of the '<em>XType</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XTYPE_FEATURE_COUNT = XELEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link xproject.xhdl.impl.XArrayImpl <em>XArray</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xproject.xhdl.impl.XArrayImpl
   * @see xproject.xhdl.impl.XhdlPackageImpl#getXArray()
   * @generated
   */
  int XARRAY = 7;

  /**
   * The number of structural features of the '<em>XArray</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XARRAY_FEATURE_COUNT = XTYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link xproject.xhdl.impl.XRangeImpl <em>XRange</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xproject.xhdl.impl.XRangeImpl
   * @see xproject.xhdl.impl.XhdlPackageImpl#getXRange()
   * @generated
   */
  int XRANGE = 8;

  /**
   * The number of structural features of the '<em>XRange</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XRANGE_FEATURE_COUNT = XTYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link xproject.xhdl.impl.XUnitsImpl <em>XUnits</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xproject.xhdl.impl.XUnitsImpl
   * @see xproject.xhdl.impl.XhdlPackageImpl#getXUnits()
   * @generated
   */
  int XUNITS = 9;

  /**
   * The number of structural features of the '<em>XUnits</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XUNITS_FEATURE_COUNT = XRANGE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link xproject.xhdl.impl.attributeImpl <em>attribute</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xproject.xhdl.impl.attributeImpl
   * @see xproject.xhdl.impl.XhdlPackageImpl#getattribute()
   * @generated
   */
  int ATTRIBUTE = 10;

  /**
   * The number of structural features of the '<em>attribute</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_FEATURE_COUNT = XATTRIBUTE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link xproject.xhdl.impl.subtypeImpl <em>subtype</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xproject.xhdl.impl.subtypeImpl
   * @see xproject.xhdl.impl.XhdlPackageImpl#getsubtype()
   * @generated
   */
  int SUBTYPE = 11;

  /**
   * The number of structural features of the '<em>subtype</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUBTYPE_FEATURE_COUNT = XSUB_TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link xproject.xhdl.impl.signalImpl <em>signal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xproject.xhdl.impl.signalImpl
   * @see xproject.xhdl.impl.XhdlPackageImpl#getsignal()
   * @generated
   */
  int SIGNAL = 12;

  /**
   * The number of structural features of the '<em>signal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIGNAL_FEATURE_COUNT = XSIGNAL_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link xproject.xhdl.impl.typeImpl <em>type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xproject.xhdl.impl.typeImpl
   * @see xproject.xhdl.impl.XhdlPackageImpl#gettype()
   * @generated
   */
  int TYPE = 13;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE__NAME = XTYPE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_FEATURE_COUNT = XTYPE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link xproject.xhdl.impl.arrayImpl <em>array</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xproject.xhdl.impl.arrayImpl
   * @see xproject.xhdl.impl.XhdlPackageImpl#getarray()
   * @generated
   */
  int ARRAY = 14;

  /**
   * The number of structural features of the '<em>array</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARRAY_FEATURE_COUNT = XARRAY_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link xproject.xhdl.impl.rangeImpl <em>range</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xproject.xhdl.impl.rangeImpl
   * @see xproject.xhdl.impl.XhdlPackageImpl#getrange()
   * @generated
   */
  int RANGE = 15;

  /**
   * The number of structural features of the '<em>range</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RANGE_FEATURE_COUNT = XRANGE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link xproject.xhdl.impl.unitsImpl <em>units</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xproject.xhdl.impl.unitsImpl
   * @see xproject.xhdl.impl.XhdlPackageImpl#getunits()
   * @generated
   */
  int UNITS = 16;

  /**
   * The feature id for the '<em><b>Units</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNITS__UNITS = XUNITS_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>units</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNITS_FEATURE_COUNT = XUNITS_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link xproject.xhdl.xhdl <em>xhdl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>xhdl</em>'.
   * @see xproject.xhdl.xhdl
   * @generated
   */
  EClass getxhdl();

  /**
   * Returns the meta object for the containment reference list '{@link xproject.xhdl.xhdl#getPackages <em>Packages</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Packages</em>'.
   * @see xproject.xhdl.xhdl#getPackages()
   * @see #getxhdl()
   * @generated
   */
  EReference getxhdl_Packages();

  /**
   * Returns the meta object for class '{@link xproject.xhdl.XPackage <em>XPackage</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>XPackage</em>'.
   * @see xproject.xhdl.XPackage
   * @generated
   */
  EClass getXPackage();

  /**
   * Returns the meta object for the attribute '{@link xproject.xhdl.XPackage#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see xproject.xhdl.XPackage#getName()
   * @see #getXPackage()
   * @generated
   */
  EAttribute getXPackage_Name();

  /**
   * Returns the meta object for the containment reference list '{@link xproject.xhdl.XPackage#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see xproject.xhdl.XPackage#getElements()
   * @see #getXPackage()
   * @generated
   */
  EReference getXPackage_Elements();

  /**
   * Returns the meta object for class '{@link xproject.xhdl.XElement <em>XElement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>XElement</em>'.
   * @see xproject.xhdl.XElement
   * @generated
   */
  EClass getXElement();

  /**
   * Returns the meta object for class '{@link xproject.xhdl.XAttribute <em>XAttribute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>XAttribute</em>'.
   * @see xproject.xhdl.XAttribute
   * @generated
   */
  EClass getXAttribute();

  /**
   * Returns the meta object for class '{@link xproject.xhdl.XSubType <em>XSub Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>XSub Type</em>'.
   * @see xproject.xhdl.XSubType
   * @generated
   */
  EClass getXSubType();

  /**
   * Returns the meta object for class '{@link xproject.xhdl.XSignal <em>XSignal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>XSignal</em>'.
   * @see xproject.xhdl.XSignal
   * @generated
   */
  EClass getXSignal();

  /**
   * Returns the meta object for class '{@link xproject.xhdl.XType <em>XType</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>XType</em>'.
   * @see xproject.xhdl.XType
   * @generated
   */
  EClass getXType();

  /**
   * Returns the meta object for class '{@link xproject.xhdl.XArray <em>XArray</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>XArray</em>'.
   * @see xproject.xhdl.XArray
   * @generated
   */
  EClass getXArray();

  /**
   * Returns the meta object for class '{@link xproject.xhdl.XRange <em>XRange</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>XRange</em>'.
   * @see xproject.xhdl.XRange
   * @generated
   */
  EClass getXRange();

  /**
   * Returns the meta object for class '{@link xproject.xhdl.XUnits <em>XUnits</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>XUnits</em>'.
   * @see xproject.xhdl.XUnits
   * @generated
   */
  EClass getXUnits();

  /**
   * Returns the meta object for class '{@link xproject.xhdl.attribute <em>attribute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>attribute</em>'.
   * @see xproject.xhdl.attribute
   * @generated
   */
  EClass getattribute();

  /**
   * Returns the meta object for class '{@link xproject.xhdl.subtype <em>subtype</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>subtype</em>'.
   * @see xproject.xhdl.subtype
   * @generated
   */
  EClass getsubtype();

  /**
   * Returns the meta object for class '{@link xproject.xhdl.signal <em>signal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>signal</em>'.
   * @see xproject.xhdl.signal
   * @generated
   */
  EClass getsignal();

  /**
   * Returns the meta object for class '{@link xproject.xhdl.type <em>type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>type</em>'.
   * @see xproject.xhdl.type
   * @generated
   */
  EClass gettype();

  /**
   * Returns the meta object for the attribute '{@link xproject.xhdl.type#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see xproject.xhdl.type#getName()
   * @see #gettype()
   * @generated
   */
  EAttribute gettype_Name();

  /**
   * Returns the meta object for class '{@link xproject.xhdl.array <em>array</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>array</em>'.
   * @see xproject.xhdl.array
   * @generated
   */
  EClass getarray();

  /**
   * Returns the meta object for class '{@link xproject.xhdl.range <em>range</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>range</em>'.
   * @see xproject.xhdl.range
   * @generated
   */
  EClass getrange();

  /**
   * Returns the meta object for class '{@link xproject.xhdl.units <em>units</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>units</em>'.
   * @see xproject.xhdl.units
   * @generated
   */
  EClass getunits();

  /**
   * Returns the meta object for the attribute list '{@link xproject.xhdl.units#getUnits <em>Units</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Units</em>'.
   * @see xproject.xhdl.units#getUnits()
   * @see #getunits()
   * @generated
   */
  EAttribute getunits_Units();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  XhdlFactory getXhdlFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link xproject.xhdl.impl.xhdlImpl <em>xhdl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xproject.xhdl.impl.xhdlImpl
     * @see xproject.xhdl.impl.XhdlPackageImpl#getxhdl()
     * @generated
     */
    EClass XHDL = eINSTANCE.getxhdl();

    /**
     * The meta object literal for the '<em><b>Packages</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference XHDL__PACKAGES = eINSTANCE.getxhdl_Packages();

    /**
     * The meta object literal for the '{@link xproject.xhdl.impl.XPackageImpl <em>XPackage</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xproject.xhdl.impl.XPackageImpl
     * @see xproject.xhdl.impl.XhdlPackageImpl#getXPackage()
     * @generated
     */
    EClass XPACKAGE = eINSTANCE.getXPackage();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute XPACKAGE__NAME = eINSTANCE.getXPackage_Name();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference XPACKAGE__ELEMENTS = eINSTANCE.getXPackage_Elements();

    /**
     * The meta object literal for the '{@link xproject.xhdl.impl.XElementImpl <em>XElement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xproject.xhdl.impl.XElementImpl
     * @see xproject.xhdl.impl.XhdlPackageImpl#getXElement()
     * @generated
     */
    EClass XELEMENT = eINSTANCE.getXElement();

    /**
     * The meta object literal for the '{@link xproject.xhdl.impl.XAttributeImpl <em>XAttribute</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xproject.xhdl.impl.XAttributeImpl
     * @see xproject.xhdl.impl.XhdlPackageImpl#getXAttribute()
     * @generated
     */
    EClass XATTRIBUTE = eINSTANCE.getXAttribute();

    /**
     * The meta object literal for the '{@link xproject.xhdl.impl.XSubTypeImpl <em>XSub Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xproject.xhdl.impl.XSubTypeImpl
     * @see xproject.xhdl.impl.XhdlPackageImpl#getXSubType()
     * @generated
     */
    EClass XSUB_TYPE = eINSTANCE.getXSubType();

    /**
     * The meta object literal for the '{@link xproject.xhdl.impl.XSignalImpl <em>XSignal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xproject.xhdl.impl.XSignalImpl
     * @see xproject.xhdl.impl.XhdlPackageImpl#getXSignal()
     * @generated
     */
    EClass XSIGNAL = eINSTANCE.getXSignal();

    /**
     * The meta object literal for the '{@link xproject.xhdl.impl.XTypeImpl <em>XType</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xproject.xhdl.impl.XTypeImpl
     * @see xproject.xhdl.impl.XhdlPackageImpl#getXType()
     * @generated
     */
    EClass XTYPE = eINSTANCE.getXType();

    /**
     * The meta object literal for the '{@link xproject.xhdl.impl.XArrayImpl <em>XArray</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xproject.xhdl.impl.XArrayImpl
     * @see xproject.xhdl.impl.XhdlPackageImpl#getXArray()
     * @generated
     */
    EClass XARRAY = eINSTANCE.getXArray();

    /**
     * The meta object literal for the '{@link xproject.xhdl.impl.XRangeImpl <em>XRange</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xproject.xhdl.impl.XRangeImpl
     * @see xproject.xhdl.impl.XhdlPackageImpl#getXRange()
     * @generated
     */
    EClass XRANGE = eINSTANCE.getXRange();

    /**
     * The meta object literal for the '{@link xproject.xhdl.impl.XUnitsImpl <em>XUnits</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xproject.xhdl.impl.XUnitsImpl
     * @see xproject.xhdl.impl.XhdlPackageImpl#getXUnits()
     * @generated
     */
    EClass XUNITS = eINSTANCE.getXUnits();

    /**
     * The meta object literal for the '{@link xproject.xhdl.impl.attributeImpl <em>attribute</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xproject.xhdl.impl.attributeImpl
     * @see xproject.xhdl.impl.XhdlPackageImpl#getattribute()
     * @generated
     */
    EClass ATTRIBUTE = eINSTANCE.getattribute();

    /**
     * The meta object literal for the '{@link xproject.xhdl.impl.subtypeImpl <em>subtype</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xproject.xhdl.impl.subtypeImpl
     * @see xproject.xhdl.impl.XhdlPackageImpl#getsubtype()
     * @generated
     */
    EClass SUBTYPE = eINSTANCE.getsubtype();

    /**
     * The meta object literal for the '{@link xproject.xhdl.impl.signalImpl <em>signal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xproject.xhdl.impl.signalImpl
     * @see xproject.xhdl.impl.XhdlPackageImpl#getsignal()
     * @generated
     */
    EClass SIGNAL = eINSTANCE.getsignal();

    /**
     * The meta object literal for the '{@link xproject.xhdl.impl.typeImpl <em>type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xproject.xhdl.impl.typeImpl
     * @see xproject.xhdl.impl.XhdlPackageImpl#gettype()
     * @generated
     */
    EClass TYPE = eINSTANCE.gettype();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TYPE__NAME = eINSTANCE.gettype_Name();

    /**
     * The meta object literal for the '{@link xproject.xhdl.impl.arrayImpl <em>array</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xproject.xhdl.impl.arrayImpl
     * @see xproject.xhdl.impl.XhdlPackageImpl#getarray()
     * @generated
     */
    EClass ARRAY = eINSTANCE.getarray();

    /**
     * The meta object literal for the '{@link xproject.xhdl.impl.rangeImpl <em>range</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xproject.xhdl.impl.rangeImpl
     * @see xproject.xhdl.impl.XhdlPackageImpl#getrange()
     * @generated
     */
    EClass RANGE = eINSTANCE.getrange();

    /**
     * The meta object literal for the '{@link xproject.xhdl.impl.unitsImpl <em>units</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xproject.xhdl.impl.unitsImpl
     * @see xproject.xhdl.impl.XhdlPackageImpl#getunits()
     * @generated
     */
    EClass UNITS = eINSTANCE.getunits();

    /**
     * The meta object literal for the '<em><b>Units</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute UNITS__UNITS = eINSTANCE.getunits_Units();

  }

} //XhdlPackage
