/**
 * generated by Xtext 2.15.0
 */
package xproject.xhdl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see xproject.xhdl.XhdlFactory
 * @model kind="package"
 * @generated
 */
public interface XhdlPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "xhdl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xproject.org/xhdl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "xhdl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  XhdlPackage eINSTANCE = xproject.xhdl.impl.XhdlPackageImpl.init();

  /**
   * The meta object id for the '{@link xproject.xhdl.impl.xhdlImpl <em>xhdl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xproject.xhdl.impl.xhdlImpl
   * @see xproject.xhdl.impl.XhdlPackageImpl#getxhdl()
   * @generated
   */
  int XHDL = 0;

  /**
   * The feature id for the '<em><b>Packages</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XHDL__PACKAGES = 0;

  /**
   * The number of structural features of the '<em>xhdl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XHDL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link xproject.xhdl.impl.XPackageRefImpl <em>XPackage Ref</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xproject.xhdl.impl.XPackageRefImpl
   * @see xproject.xhdl.impl.XhdlPackageImpl#getXPackageRef()
   * @generated
   */
  int XPACKAGE_REF = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XPACKAGE_REF__NAME = 0;

  /**
   * The number of structural features of the '<em>XPackage Ref</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XPACKAGE_REF_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link xproject.xhdl.impl.XPackageImpl <em>XPackage</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xproject.xhdl.impl.XPackageImpl
   * @see xproject.xhdl.impl.XhdlPackageImpl#getXPackage()
   * @generated
   */
  int XPACKAGE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XPACKAGE__NAME = 0;

  /**
   * The feature id for the '<em><b>Xis</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XPACKAGE__XIS = 1;

  /**
   * The feature id for the '<em><b>Xend</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XPACKAGE__XEND = 2;

  /**
   * The number of structural features of the '<em>XPackage</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XPACKAGE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link xproject.xhdl.impl.XTypeRefImpl <em>XType Ref</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xproject.xhdl.impl.XTypeRefImpl
   * @see xproject.xhdl.impl.XhdlPackageImpl#getXTypeRef()
   * @generated
   */
  int XTYPE_REF = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XTYPE_REF__NAME = 0;

  /**
   * The number of structural features of the '<em>XType Ref</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XTYPE_REF_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link xproject.xhdl.impl.XElementImpl <em>XElement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xproject.xhdl.impl.XElementImpl
   * @see xproject.xhdl.impl.XhdlPackageImpl#getXElement()
   * @generated
   */
  int XELEMENT = 4;

  /**
   * The number of structural features of the '<em>XElement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XELEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link xproject.xhdl.impl.XAttributeImpl <em>XAttribute</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xproject.xhdl.impl.XAttributeImpl
   * @see xproject.xhdl.impl.XhdlPackageImpl#getXAttribute()
   * @generated
   */
  int XATTRIBUTE = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XATTRIBUTE__NAME = XELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Xtype</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XATTRIBUTE__XTYPE = XELEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>XAttribute</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XATTRIBUTE_FEATURE_COUNT = XELEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link xproject.xhdl.impl.XSubTypeImpl <em>XSub Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xproject.xhdl.impl.XSubTypeImpl
   * @see xproject.xhdl.impl.XhdlPackageImpl#getXSubType()
   * @generated
   */
  int XSUB_TYPE = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XSUB_TYPE__NAME = XELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Xis</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XSUB_TYPE__XIS = XELEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>XSub Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XSUB_TYPE_FEATURE_COUNT = XELEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link xproject.xhdl.impl.XSignalImpl <em>XSignal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xproject.xhdl.impl.XSignalImpl
   * @see xproject.xhdl.impl.XhdlPackageImpl#getXSignal()
   * @generated
   */
  int XSIGNAL = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XSIGNAL__NAME = XELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Xtype</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XSIGNAL__XTYPE = XELEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>XSignal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XSIGNAL_FEATURE_COUNT = XELEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link xproject.xhdl.impl.XTypeImpl <em>XType</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xproject.xhdl.impl.XTypeImpl
   * @see xproject.xhdl.impl.XhdlPackageImpl#getXType()
   * @generated
   */
  int XTYPE = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XTYPE__NAME = XELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Xenums</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XTYPE__XENUMS = XELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Xrange</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XTYPE__XRANGE = XELEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Xarray</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XTYPE__XARRAY = XELEMENT_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>XType</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XTYPE_FEATURE_COUNT = XELEMENT_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link xproject.xhdl.impl.XArrayImpl <em>XArray</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xproject.xhdl.impl.XArrayImpl
   * @see xproject.xhdl.impl.XhdlPackageImpl#getXArray()
   * @generated
   */
  int XARRAY = 9;

  /**
   * The feature id for the '<em><b>Xrange</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XARRAY__XRANGE = 0;

  /**
   * The feature id for the '<em><b>Xof</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XARRAY__XOF = 1;

  /**
   * The number of structural features of the '<em>XArray</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XARRAY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link xproject.xhdl.impl.XRangeImpl <em>XRange</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xproject.xhdl.impl.XRangeImpl
   * @see xproject.xhdl.impl.XhdlPackageImpl#getXRange()
   * @generated
   */
  int XRANGE = 10;

  /**
   * The feature id for the '<em><b>Xfrom</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XRANGE__XFROM = 0;

  /**
   * The feature id for the '<em><b>Xto</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XRANGE__XTO = 1;

  /**
   * The feature id for the '<em><b>Xunits</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XRANGE__XUNITS = 2;

  /**
   * The number of structural features of the '<em>XRange</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XRANGE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link xproject.xhdl.impl.XRangeValueImpl <em>XRange Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xproject.xhdl.impl.XRangeValueImpl
   * @see xproject.xhdl.impl.XhdlPackageImpl#getXRangeValue()
   * @generated
   */
  int XRANGE_VALUE = 11;

  /**
   * The feature id for the '<em><b>Xvalue</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XRANGE_VALUE__XVALUE = 0;

  /**
   * The feature id for the '<em><b>Xunit</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XRANGE_VALUE__XUNIT = 1;

  /**
   * The number of structural features of the '<em>XRange Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XRANGE_VALUE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link xproject.xhdl.impl.XUnitsImpl <em>XUnits</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xproject.xhdl.impl.XUnitsImpl
   * @see xproject.xhdl.impl.XhdlPackageImpl#getXUnits()
   * @generated
   */
  int XUNITS = 12;

  /**
   * The feature id for the '<em><b>Xunits</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XUNITS__XUNITS = 0;

  /**
   * The number of structural features of the '<em>XUnits</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XUNITS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link xproject.xhdl.impl.XUnitRefImpl <em>XUnit Ref</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xproject.xhdl.impl.XUnitRefImpl
   * @see xproject.xhdl.impl.XhdlPackageImpl#getXUnitRef()
   * @generated
   */
  int XUNIT_REF = 13;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XUNIT_REF__NAME = 0;

  /**
   * The number of structural features of the '<em>XUnit Ref</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XUNIT_REF_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link xproject.xhdl.impl.XUnitImpl <em>XUnit</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xproject.xhdl.impl.XUnitImpl
   * @see xproject.xhdl.impl.XhdlPackageImpl#getXUnit()
   * @generated
   */
  int XUNIT = 14;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XUNIT__NAME = 0;

  /**
   * The feature id for the '<em><b>Xvalue</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XUNIT__XVALUE = 1;

  /**
   * The feature id for the '<em><b>Xbased</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XUNIT__XBASED = 2;

  /**
   * The number of structural features of the '<em>XUnit</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XUNIT_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link xproject.xhdl.impl.XEnumsImpl <em>XEnums</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xproject.xhdl.impl.XEnumsImpl
   * @see xproject.xhdl.impl.XhdlPackageImpl#getXEnums()
   * @generated
   */
  int XENUMS = 15;

  /**
   * The feature id for the '<em><b>Xenums</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XENUMS__XENUMS = 0;

  /**
   * The number of structural features of the '<em>XEnums</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XENUMS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link xproject.xhdl.impl.XFunctionRefImpl <em>XFunction Ref</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xproject.xhdl.impl.XFunctionRefImpl
   * @see xproject.xhdl.impl.XhdlPackageImpl#getXFunctionRef()
   * @generated
   */
  int XFUNCTION_REF = 16;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XFUNCTION_REF__NAME = 0;

  /**
   * The feature id for the '<em><b>Xreturn</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XFUNCTION_REF__XRETURN = 1;

  /**
   * The number of structural features of the '<em>XFunction Ref</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XFUNCTION_REF_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link xproject.xhdl.impl.XImpureImpl <em>XImpure</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see xproject.xhdl.impl.XImpureImpl
   * @see xproject.xhdl.impl.XhdlPackageImpl#getXImpure()
   * @generated
   */
  int XIMPURE = 17;

  /**
   * The feature id for the '<em><b>Xfunc</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XIMPURE__XFUNC = XELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>XImpure</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int XIMPURE_FEATURE_COUNT = XELEMENT_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link xproject.xhdl.xhdl <em>xhdl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>xhdl</em>'.
   * @see xproject.xhdl.xhdl
   * @generated
   */
  EClass getxhdl();

  /**
   * Returns the meta object for the containment reference list '{@link xproject.xhdl.xhdl#getPackages <em>Packages</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Packages</em>'.
   * @see xproject.xhdl.xhdl#getPackages()
   * @see #getxhdl()
   * @generated
   */
  EReference getxhdl_Packages();

  /**
   * Returns the meta object for class '{@link xproject.xhdl.XPackageRef <em>XPackage Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>XPackage Ref</em>'.
   * @see xproject.xhdl.XPackageRef
   * @generated
   */
  EClass getXPackageRef();

  /**
   * Returns the meta object for the attribute '{@link xproject.xhdl.XPackageRef#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see xproject.xhdl.XPackageRef#getName()
   * @see #getXPackageRef()
   * @generated
   */
  EAttribute getXPackageRef_Name();

  /**
   * Returns the meta object for class '{@link xproject.xhdl.XPackage <em>XPackage</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>XPackage</em>'.
   * @see xproject.xhdl.XPackage
   * @generated
   */
  EClass getXPackage();

  /**
   * Returns the meta object for the attribute '{@link xproject.xhdl.XPackage#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see xproject.xhdl.XPackage#getName()
   * @see #getXPackage()
   * @generated
   */
  EAttribute getXPackage_Name();

  /**
   * Returns the meta object for the containment reference list '{@link xproject.xhdl.XPackage#getXis <em>Xis</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Xis</em>'.
   * @see xproject.xhdl.XPackage#getXis()
   * @see #getXPackage()
   * @generated
   */
  EReference getXPackage_Xis();

  /**
   * Returns the meta object for the reference '{@link xproject.xhdl.XPackage#getXend <em>Xend</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Xend</em>'.
   * @see xproject.xhdl.XPackage#getXend()
   * @see #getXPackage()
   * @generated
   */
  EReference getXPackage_Xend();

  /**
   * Returns the meta object for class '{@link xproject.xhdl.XTypeRef <em>XType Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>XType Ref</em>'.
   * @see xproject.xhdl.XTypeRef
   * @generated
   */
  EClass getXTypeRef();

  /**
   * Returns the meta object for the attribute '{@link xproject.xhdl.XTypeRef#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see xproject.xhdl.XTypeRef#getName()
   * @see #getXTypeRef()
   * @generated
   */
  EAttribute getXTypeRef_Name();

  /**
   * Returns the meta object for class '{@link xproject.xhdl.XElement <em>XElement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>XElement</em>'.
   * @see xproject.xhdl.XElement
   * @generated
   */
  EClass getXElement();

  /**
   * Returns the meta object for class '{@link xproject.xhdl.XAttribute <em>XAttribute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>XAttribute</em>'.
   * @see xproject.xhdl.XAttribute
   * @generated
   */
  EClass getXAttribute();

  /**
   * Returns the meta object for the attribute '{@link xproject.xhdl.XAttribute#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see xproject.xhdl.XAttribute#getName()
   * @see #getXAttribute()
   * @generated
   */
  EAttribute getXAttribute_Name();

  /**
   * Returns the meta object for the reference '{@link xproject.xhdl.XAttribute#getXtype <em>Xtype</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Xtype</em>'.
   * @see xproject.xhdl.XAttribute#getXtype()
   * @see #getXAttribute()
   * @generated
   */
  EReference getXAttribute_Xtype();

  /**
   * Returns the meta object for class '{@link xproject.xhdl.XSubType <em>XSub Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>XSub Type</em>'.
   * @see xproject.xhdl.XSubType
   * @generated
   */
  EClass getXSubType();

  /**
   * Returns the meta object for the attribute '{@link xproject.xhdl.XSubType#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see xproject.xhdl.XSubType#getName()
   * @see #getXSubType()
   * @generated
   */
  EAttribute getXSubType_Name();

  /**
   * Returns the meta object for the reference '{@link xproject.xhdl.XSubType#getXis <em>Xis</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Xis</em>'.
   * @see xproject.xhdl.XSubType#getXis()
   * @see #getXSubType()
   * @generated
   */
  EReference getXSubType_Xis();

  /**
   * Returns the meta object for class '{@link xproject.xhdl.XSignal <em>XSignal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>XSignal</em>'.
   * @see xproject.xhdl.XSignal
   * @generated
   */
  EClass getXSignal();

  /**
   * Returns the meta object for the attribute '{@link xproject.xhdl.XSignal#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see xproject.xhdl.XSignal#getName()
   * @see #getXSignal()
   * @generated
   */
  EAttribute getXSignal_Name();

  /**
   * Returns the meta object for the reference '{@link xproject.xhdl.XSignal#getXtype <em>Xtype</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Xtype</em>'.
   * @see xproject.xhdl.XSignal#getXtype()
   * @see #getXSignal()
   * @generated
   */
  EReference getXSignal_Xtype();

  /**
   * Returns the meta object for class '{@link xproject.xhdl.XType <em>XType</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>XType</em>'.
   * @see xproject.xhdl.XType
   * @generated
   */
  EClass getXType();

  /**
   * Returns the meta object for the attribute '{@link xproject.xhdl.XType#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see xproject.xhdl.XType#getName()
   * @see #getXType()
   * @generated
   */
  EAttribute getXType_Name();

  /**
   * Returns the meta object for the containment reference '{@link xproject.xhdl.XType#getXenums <em>Xenums</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Xenums</em>'.
   * @see xproject.xhdl.XType#getXenums()
   * @see #getXType()
   * @generated
   */
  EReference getXType_Xenums();

  /**
   * Returns the meta object for the containment reference '{@link xproject.xhdl.XType#getXrange <em>Xrange</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Xrange</em>'.
   * @see xproject.xhdl.XType#getXrange()
   * @see #getXType()
   * @generated
   */
  EReference getXType_Xrange();

  /**
   * Returns the meta object for the containment reference '{@link xproject.xhdl.XType#getXarray <em>Xarray</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Xarray</em>'.
   * @see xproject.xhdl.XType#getXarray()
   * @see #getXType()
   * @generated
   */
  EReference getXType_Xarray();

  /**
   * Returns the meta object for class '{@link xproject.xhdl.XArray <em>XArray</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>XArray</em>'.
   * @see xproject.xhdl.XArray
   * @generated
   */
  EClass getXArray();

  /**
   * Returns the meta object for the reference '{@link xproject.xhdl.XArray#getXrange <em>Xrange</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Xrange</em>'.
   * @see xproject.xhdl.XArray#getXrange()
   * @see #getXArray()
   * @generated
   */
  EReference getXArray_Xrange();

  /**
   * Returns the meta object for the reference '{@link xproject.xhdl.XArray#getXof <em>Xof</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Xof</em>'.
   * @see xproject.xhdl.XArray#getXof()
   * @see #getXArray()
   * @generated
   */
  EReference getXArray_Xof();

  /**
   * Returns the meta object for class '{@link xproject.xhdl.XRange <em>XRange</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>XRange</em>'.
   * @see xproject.xhdl.XRange
   * @generated
   */
  EClass getXRange();

  /**
   * Returns the meta object for the reference '{@link xproject.xhdl.XRange#getXfrom <em>Xfrom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Xfrom</em>'.
   * @see xproject.xhdl.XRange#getXfrom()
   * @see #getXRange()
   * @generated
   */
  EReference getXRange_Xfrom();

  /**
   * Returns the meta object for the reference '{@link xproject.xhdl.XRange#getXto <em>Xto</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Xto</em>'.
   * @see xproject.xhdl.XRange#getXto()
   * @see #getXRange()
   * @generated
   */
  EReference getXRange_Xto();

  /**
   * Returns the meta object for the containment reference '{@link xproject.xhdl.XRange#getXunits <em>Xunits</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Xunits</em>'.
   * @see xproject.xhdl.XRange#getXunits()
   * @see #getXRange()
   * @generated
   */
  EReference getXRange_Xunits();

  /**
   * Returns the meta object for class '{@link xproject.xhdl.XRangeValue <em>XRange Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>XRange Value</em>'.
   * @see xproject.xhdl.XRangeValue
   * @generated
   */
  EClass getXRangeValue();

  /**
   * Returns the meta object for the attribute '{@link xproject.xhdl.XRangeValue#getXvalue <em>Xvalue</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Xvalue</em>'.
   * @see xproject.xhdl.XRangeValue#getXvalue()
   * @see #getXRangeValue()
   * @generated
   */
  EAttribute getXRangeValue_Xvalue();

  /**
   * Returns the meta object for the reference '{@link xproject.xhdl.XRangeValue#getXunit <em>Xunit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Xunit</em>'.
   * @see xproject.xhdl.XRangeValue#getXunit()
   * @see #getXRangeValue()
   * @generated
   */
  EReference getXRangeValue_Xunit();

  /**
   * Returns the meta object for class '{@link xproject.xhdl.XUnits <em>XUnits</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>XUnits</em>'.
   * @see xproject.xhdl.XUnits
   * @generated
   */
  EClass getXUnits();

  /**
   * Returns the meta object for the containment reference list '{@link xproject.xhdl.XUnits#getXunits <em>Xunits</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Xunits</em>'.
   * @see xproject.xhdl.XUnits#getXunits()
   * @see #getXUnits()
   * @generated
   */
  EReference getXUnits_Xunits();

  /**
   * Returns the meta object for class '{@link xproject.xhdl.XUnitRef <em>XUnit Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>XUnit Ref</em>'.
   * @see xproject.xhdl.XUnitRef
   * @generated
   */
  EClass getXUnitRef();

  /**
   * Returns the meta object for the attribute '{@link xproject.xhdl.XUnitRef#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see xproject.xhdl.XUnitRef#getName()
   * @see #getXUnitRef()
   * @generated
   */
  EAttribute getXUnitRef_Name();

  /**
   * Returns the meta object for class '{@link xproject.xhdl.XUnit <em>XUnit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>XUnit</em>'.
   * @see xproject.xhdl.XUnit
   * @generated
   */
  EClass getXUnit();

  /**
   * Returns the meta object for the attribute '{@link xproject.xhdl.XUnit#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see xproject.xhdl.XUnit#getName()
   * @see #getXUnit()
   * @generated
   */
  EAttribute getXUnit_Name();

  /**
   * Returns the meta object for the attribute '{@link xproject.xhdl.XUnit#getXvalue <em>Xvalue</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Xvalue</em>'.
   * @see xproject.xhdl.XUnit#getXvalue()
   * @see #getXUnit()
   * @generated
   */
  EAttribute getXUnit_Xvalue();

  /**
   * Returns the meta object for the reference '{@link xproject.xhdl.XUnit#getXbased <em>Xbased</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Xbased</em>'.
   * @see xproject.xhdl.XUnit#getXbased()
   * @see #getXUnit()
   * @generated
   */
  EReference getXUnit_Xbased();

  /**
   * Returns the meta object for class '{@link xproject.xhdl.XEnums <em>XEnums</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>XEnums</em>'.
   * @see xproject.xhdl.XEnums
   * @generated
   */
  EClass getXEnums();

  /**
   * Returns the meta object for the attribute list '{@link xproject.xhdl.XEnums#getXenums <em>Xenums</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Xenums</em>'.
   * @see xproject.xhdl.XEnums#getXenums()
   * @see #getXEnums()
   * @generated
   */
  EAttribute getXEnums_Xenums();

  /**
   * Returns the meta object for class '{@link xproject.xhdl.XFunctionRef <em>XFunction Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>XFunction Ref</em>'.
   * @see xproject.xhdl.XFunctionRef
   * @generated
   */
  EClass getXFunctionRef();

  /**
   * Returns the meta object for the attribute '{@link xproject.xhdl.XFunctionRef#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see xproject.xhdl.XFunctionRef#getName()
   * @see #getXFunctionRef()
   * @generated
   */
  EAttribute getXFunctionRef_Name();

  /**
   * Returns the meta object for the reference '{@link xproject.xhdl.XFunctionRef#getXreturn <em>Xreturn</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Xreturn</em>'.
   * @see xproject.xhdl.XFunctionRef#getXreturn()
   * @see #getXFunctionRef()
   * @generated
   */
  EReference getXFunctionRef_Xreturn();

  /**
   * Returns the meta object for class '{@link xproject.xhdl.XImpure <em>XImpure</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>XImpure</em>'.
   * @see xproject.xhdl.XImpure
   * @generated
   */
  EClass getXImpure();

  /**
   * Returns the meta object for the reference '{@link xproject.xhdl.XImpure#getXfunc <em>Xfunc</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Xfunc</em>'.
   * @see xproject.xhdl.XImpure#getXfunc()
   * @see #getXImpure()
   * @generated
   */
  EReference getXImpure_Xfunc();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  XhdlFactory getXhdlFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link xproject.xhdl.impl.xhdlImpl <em>xhdl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xproject.xhdl.impl.xhdlImpl
     * @see xproject.xhdl.impl.XhdlPackageImpl#getxhdl()
     * @generated
     */
    EClass XHDL = eINSTANCE.getxhdl();

    /**
     * The meta object literal for the '<em><b>Packages</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference XHDL__PACKAGES = eINSTANCE.getxhdl_Packages();

    /**
     * The meta object literal for the '{@link xproject.xhdl.impl.XPackageRefImpl <em>XPackage Ref</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xproject.xhdl.impl.XPackageRefImpl
     * @see xproject.xhdl.impl.XhdlPackageImpl#getXPackageRef()
     * @generated
     */
    EClass XPACKAGE_REF = eINSTANCE.getXPackageRef();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute XPACKAGE_REF__NAME = eINSTANCE.getXPackageRef_Name();

    /**
     * The meta object literal for the '{@link xproject.xhdl.impl.XPackageImpl <em>XPackage</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xproject.xhdl.impl.XPackageImpl
     * @see xproject.xhdl.impl.XhdlPackageImpl#getXPackage()
     * @generated
     */
    EClass XPACKAGE = eINSTANCE.getXPackage();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute XPACKAGE__NAME = eINSTANCE.getXPackage_Name();

    /**
     * The meta object literal for the '<em><b>Xis</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference XPACKAGE__XIS = eINSTANCE.getXPackage_Xis();

    /**
     * The meta object literal for the '<em><b>Xend</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference XPACKAGE__XEND = eINSTANCE.getXPackage_Xend();

    /**
     * The meta object literal for the '{@link xproject.xhdl.impl.XTypeRefImpl <em>XType Ref</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xproject.xhdl.impl.XTypeRefImpl
     * @see xproject.xhdl.impl.XhdlPackageImpl#getXTypeRef()
     * @generated
     */
    EClass XTYPE_REF = eINSTANCE.getXTypeRef();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute XTYPE_REF__NAME = eINSTANCE.getXTypeRef_Name();

    /**
     * The meta object literal for the '{@link xproject.xhdl.impl.XElementImpl <em>XElement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xproject.xhdl.impl.XElementImpl
     * @see xproject.xhdl.impl.XhdlPackageImpl#getXElement()
     * @generated
     */
    EClass XELEMENT = eINSTANCE.getXElement();

    /**
     * The meta object literal for the '{@link xproject.xhdl.impl.XAttributeImpl <em>XAttribute</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xproject.xhdl.impl.XAttributeImpl
     * @see xproject.xhdl.impl.XhdlPackageImpl#getXAttribute()
     * @generated
     */
    EClass XATTRIBUTE = eINSTANCE.getXAttribute();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute XATTRIBUTE__NAME = eINSTANCE.getXAttribute_Name();

    /**
     * The meta object literal for the '<em><b>Xtype</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference XATTRIBUTE__XTYPE = eINSTANCE.getXAttribute_Xtype();

    /**
     * The meta object literal for the '{@link xproject.xhdl.impl.XSubTypeImpl <em>XSub Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xproject.xhdl.impl.XSubTypeImpl
     * @see xproject.xhdl.impl.XhdlPackageImpl#getXSubType()
     * @generated
     */
    EClass XSUB_TYPE = eINSTANCE.getXSubType();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute XSUB_TYPE__NAME = eINSTANCE.getXSubType_Name();

    /**
     * The meta object literal for the '<em><b>Xis</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference XSUB_TYPE__XIS = eINSTANCE.getXSubType_Xis();

    /**
     * The meta object literal for the '{@link xproject.xhdl.impl.XSignalImpl <em>XSignal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xproject.xhdl.impl.XSignalImpl
     * @see xproject.xhdl.impl.XhdlPackageImpl#getXSignal()
     * @generated
     */
    EClass XSIGNAL = eINSTANCE.getXSignal();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute XSIGNAL__NAME = eINSTANCE.getXSignal_Name();

    /**
     * The meta object literal for the '<em><b>Xtype</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference XSIGNAL__XTYPE = eINSTANCE.getXSignal_Xtype();

    /**
     * The meta object literal for the '{@link xproject.xhdl.impl.XTypeImpl <em>XType</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xproject.xhdl.impl.XTypeImpl
     * @see xproject.xhdl.impl.XhdlPackageImpl#getXType()
     * @generated
     */
    EClass XTYPE = eINSTANCE.getXType();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute XTYPE__NAME = eINSTANCE.getXType_Name();

    /**
     * The meta object literal for the '<em><b>Xenums</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference XTYPE__XENUMS = eINSTANCE.getXType_Xenums();

    /**
     * The meta object literal for the '<em><b>Xrange</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference XTYPE__XRANGE = eINSTANCE.getXType_Xrange();

    /**
     * The meta object literal for the '<em><b>Xarray</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference XTYPE__XARRAY = eINSTANCE.getXType_Xarray();

    /**
     * The meta object literal for the '{@link xproject.xhdl.impl.XArrayImpl <em>XArray</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xproject.xhdl.impl.XArrayImpl
     * @see xproject.xhdl.impl.XhdlPackageImpl#getXArray()
     * @generated
     */
    EClass XARRAY = eINSTANCE.getXArray();

    /**
     * The meta object literal for the '<em><b>Xrange</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference XARRAY__XRANGE = eINSTANCE.getXArray_Xrange();

    /**
     * The meta object literal for the '<em><b>Xof</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference XARRAY__XOF = eINSTANCE.getXArray_Xof();

    /**
     * The meta object literal for the '{@link xproject.xhdl.impl.XRangeImpl <em>XRange</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xproject.xhdl.impl.XRangeImpl
     * @see xproject.xhdl.impl.XhdlPackageImpl#getXRange()
     * @generated
     */
    EClass XRANGE = eINSTANCE.getXRange();

    /**
     * The meta object literal for the '<em><b>Xfrom</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference XRANGE__XFROM = eINSTANCE.getXRange_Xfrom();

    /**
     * The meta object literal for the '<em><b>Xto</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference XRANGE__XTO = eINSTANCE.getXRange_Xto();

    /**
     * The meta object literal for the '<em><b>Xunits</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference XRANGE__XUNITS = eINSTANCE.getXRange_Xunits();

    /**
     * The meta object literal for the '{@link xproject.xhdl.impl.XRangeValueImpl <em>XRange Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xproject.xhdl.impl.XRangeValueImpl
     * @see xproject.xhdl.impl.XhdlPackageImpl#getXRangeValue()
     * @generated
     */
    EClass XRANGE_VALUE = eINSTANCE.getXRangeValue();

    /**
     * The meta object literal for the '<em><b>Xvalue</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute XRANGE_VALUE__XVALUE = eINSTANCE.getXRangeValue_Xvalue();

    /**
     * The meta object literal for the '<em><b>Xunit</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference XRANGE_VALUE__XUNIT = eINSTANCE.getXRangeValue_Xunit();

    /**
     * The meta object literal for the '{@link xproject.xhdl.impl.XUnitsImpl <em>XUnits</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xproject.xhdl.impl.XUnitsImpl
     * @see xproject.xhdl.impl.XhdlPackageImpl#getXUnits()
     * @generated
     */
    EClass XUNITS = eINSTANCE.getXUnits();

    /**
     * The meta object literal for the '<em><b>Xunits</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference XUNITS__XUNITS = eINSTANCE.getXUnits_Xunits();

    /**
     * The meta object literal for the '{@link xproject.xhdl.impl.XUnitRefImpl <em>XUnit Ref</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xproject.xhdl.impl.XUnitRefImpl
     * @see xproject.xhdl.impl.XhdlPackageImpl#getXUnitRef()
     * @generated
     */
    EClass XUNIT_REF = eINSTANCE.getXUnitRef();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute XUNIT_REF__NAME = eINSTANCE.getXUnitRef_Name();

    /**
     * The meta object literal for the '{@link xproject.xhdl.impl.XUnitImpl <em>XUnit</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xproject.xhdl.impl.XUnitImpl
     * @see xproject.xhdl.impl.XhdlPackageImpl#getXUnit()
     * @generated
     */
    EClass XUNIT = eINSTANCE.getXUnit();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute XUNIT__NAME = eINSTANCE.getXUnit_Name();

    /**
     * The meta object literal for the '<em><b>Xvalue</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute XUNIT__XVALUE = eINSTANCE.getXUnit_Xvalue();

    /**
     * The meta object literal for the '<em><b>Xbased</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference XUNIT__XBASED = eINSTANCE.getXUnit_Xbased();

    /**
     * The meta object literal for the '{@link xproject.xhdl.impl.XEnumsImpl <em>XEnums</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xproject.xhdl.impl.XEnumsImpl
     * @see xproject.xhdl.impl.XhdlPackageImpl#getXEnums()
     * @generated
     */
    EClass XENUMS = eINSTANCE.getXEnums();

    /**
     * The meta object literal for the '<em><b>Xenums</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute XENUMS__XENUMS = eINSTANCE.getXEnums_Xenums();

    /**
     * The meta object literal for the '{@link xproject.xhdl.impl.XFunctionRefImpl <em>XFunction Ref</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xproject.xhdl.impl.XFunctionRefImpl
     * @see xproject.xhdl.impl.XhdlPackageImpl#getXFunctionRef()
     * @generated
     */
    EClass XFUNCTION_REF = eINSTANCE.getXFunctionRef();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute XFUNCTION_REF__NAME = eINSTANCE.getXFunctionRef_Name();

    /**
     * The meta object literal for the '<em><b>Xreturn</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference XFUNCTION_REF__XRETURN = eINSTANCE.getXFunctionRef_Xreturn();

    /**
     * The meta object literal for the '{@link xproject.xhdl.impl.XImpureImpl <em>XImpure</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see xproject.xhdl.impl.XImpureImpl
     * @see xproject.xhdl.impl.XhdlPackageImpl#getXImpure()
     * @generated
     */
    EClass XIMPURE = eINSTANCE.getXImpure();

    /**
     * The meta object literal for the '<em><b>Xfunc</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference XIMPURE__XFUNC = eINSTANCE.getXImpure_Xfunc();

  }

} //XhdlPackage
