/**
 * generated by Xtext 2.15.0
 */
package xproject.xhdl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>xhdl</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xproject.xhdl.xhdl#getPackages <em>Packages</em>}</li>
 * </ul>
 *
 * @see xproject.xhdl.XhdlPackage#getxhdl()
 * @model
 * @generated
 */
public interface xhdl extends EObject
{
  /**
   * Returns the value of the '<em><b>Packages</b></em>' containment reference list.
   * The list contents are of type {@link xproject.xhdl.XPackage}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Packages</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Packages</em>' containment reference list.
   * @see xproject.xhdl.XhdlPackage#getxhdl_Packages()
   * @model containment="true"
   * @generated
   */
  EList<XPackage> getPackages();

} // xhdl
