/**
 * generated by Xtext 2.15.0
 */
package xproject.xhdl;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see xproject.xhdl.XhdlPackage
 * @generated
 */
public interface XhdlFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  XhdlFactory eINSTANCE = xproject.xhdl.impl.XhdlFactoryImpl.init();

  /**
   * Returns a new object of class '<em>xhdl</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>xhdl</em>'.
   * @generated
   */
  xhdl createxhdl();

  /**
   * Returns a new object of class '<em>XPackage Ref</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>XPackage Ref</em>'.
   * @generated
   */
  XPackageRef createXPackageRef();

  /**
   * Returns a new object of class '<em>XPackage</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>XPackage</em>'.
   * @generated
   */
  XPackage createXPackage();

  /**
   * Returns a new object of class '<em>XType Ref</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>XType Ref</em>'.
   * @generated
   */
  XTypeRef createXTypeRef();

  /**
   * Returns a new object of class '<em>XElement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>XElement</em>'.
   * @generated
   */
  XElement createXElement();

  /**
   * Returns a new object of class '<em>XAttribute</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>XAttribute</em>'.
   * @generated
   */
  XAttribute createXAttribute();

  /**
   * Returns a new object of class '<em>XSub Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>XSub Type</em>'.
   * @generated
   */
  XSubType createXSubType();

  /**
   * Returns a new object of class '<em>XSignal</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>XSignal</em>'.
   * @generated
   */
  XSignal createXSignal();

  /**
   * Returns a new object of class '<em>XType</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>XType</em>'.
   * @generated
   */
  XType createXType();

  /**
   * Returns a new object of class '<em>XArray</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>XArray</em>'.
   * @generated
   */
  XArray createXArray();

  /**
   * Returns a new object of class '<em>XRange</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>XRange</em>'.
   * @generated
   */
  XRange createXRange();

  /**
   * Returns a new object of class '<em>XRange Value</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>XRange Value</em>'.
   * @generated
   */
  XRangeValue createXRangeValue();

  /**
   * Returns a new object of class '<em>XUnits</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>XUnits</em>'.
   * @generated
   */
  XUnits createXUnits();

  /**
   * Returns a new object of class '<em>XUnit Ref</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>XUnit Ref</em>'.
   * @generated
   */
  XUnitRef createXUnitRef();

  /**
   * Returns a new object of class '<em>XUnit</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>XUnit</em>'.
   * @generated
   */
  XUnit createXUnit();

  /**
   * Returns a new object of class '<em>XEnums</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>XEnums</em>'.
   * @generated
   */
  XEnums createXEnums();

  /**
   * Returns a new object of class '<em>XFunction Ref</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>XFunction Ref</em>'.
   * @generated
   */
  XFunctionRef createXFunctionRef();

  /**
   * Returns a new object of class '<em>XImpure</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>XImpure</em>'.
   * @generated
   */
  XImpure createXImpure();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  XhdlPackage getXhdlPackage();

} //XhdlFactory
