/**
 * generated by Xtext 2.15.0
 */
package xproject.xhdl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>XPackage</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xproject.xhdl.XPackage#getName <em>Name</em>}</li>
 *   <li>{@link xproject.xhdl.XPackage#getXis <em>Xis</em>}</li>
 *   <li>{@link xproject.xhdl.XPackage#getXend <em>Xend</em>}</li>
 * </ul>
 *
 * @see xproject.xhdl.XhdlPackage#getXPackage()
 * @model
 * @generated
 */
public interface XPackage extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see xproject.xhdl.XhdlPackage#getXPackage_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link xproject.xhdl.XPackage#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Xis</b></em>' containment reference list.
   * The list contents are of type {@link xproject.xhdl.XElement}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Xis</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Xis</em>' containment reference list.
   * @see xproject.xhdl.XhdlPackage#getXPackage_Xis()
   * @model containment="true"
   * @generated
   */
  EList<XElement> getXis();

  /**
   * Returns the value of the '<em><b>Xend</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Xend</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Xend</em>' containment reference.
   * @see #setXend(XPackageRef)
   * @see xproject.xhdl.XhdlPackage#getXPackage_Xend()
   * @model containment="true"
   * @generated
   */
  XPackageRef getXend();

  /**
   * Sets the value of the '{@link xproject.xhdl.XPackage#getXend <em>Xend</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Xend</em>' containment reference.
   * @see #getXend()
   * @generated
   */
  void setXend(XPackageRef value);

} // XPackage
