/**
 * generated by Xtext 2.15.0
 */
package xproject.xhdl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>XRange Value</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xproject.xhdl.XRangeValue#getXlvalue <em>Xlvalue</em>}</li>
 *   <li>{@link xproject.xhdl.XRangeValue#getXdvalue <em>Xdvalue</em>}</li>
 *   <li>{@link xproject.xhdl.XRangeValue#getXunit <em>Xunit</em>}</li>
 * </ul>
 *
 * @see xproject.xhdl.XhdlPackage#getXRangeValue()
 * @model
 * @generated
 */
public interface XRangeValue extends EObject
{
  /**
   * Returns the value of the '<em><b>Xlvalue</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Xlvalue</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Xlvalue</em>' attribute.
   * @see #setXlvalue(long)
   * @see xproject.xhdl.XhdlPackage#getXRangeValue_Xlvalue()
   * @model
   * @generated
   */
  long getXlvalue();

  /**
   * Sets the value of the '{@link xproject.xhdl.XRangeValue#getXlvalue <em>Xlvalue</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Xlvalue</em>' attribute.
   * @see #getXlvalue()
   * @generated
   */
  void setXlvalue(long value);

  /**
   * Returns the value of the '<em><b>Xdvalue</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Xdvalue</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Xdvalue</em>' attribute.
   * @see #setXdvalue(double)
   * @see xproject.xhdl.XhdlPackage#getXRangeValue_Xdvalue()
   * @model
   * @generated
   */
  double getXdvalue();

  /**
   * Sets the value of the '{@link xproject.xhdl.XRangeValue#getXdvalue <em>Xdvalue</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Xdvalue</em>' attribute.
   * @see #getXdvalue()
   * @generated
   */
  void setXdvalue(double value);

  /**
   * Returns the value of the '<em><b>Xunit</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Xunit</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Xunit</em>' containment reference.
   * @see #setXunit(XUnitRef)
   * @see xproject.xhdl.XhdlPackage#getXRangeValue_Xunit()
   * @model containment="true"
   * @generated
   */
  XUnitRef getXunit();

  /**
   * Sets the value of the '{@link xproject.xhdl.XRangeValue#getXunit <em>Xunit</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Xunit</em>' containment reference.
   * @see #getXunit()
   * @generated
   */
  void setXunit(XUnitRef value);

} // XRangeValue
