/**
 * generated by Xtext 2.15.0
 */
package xproject.xhdl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>XSub Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link xproject.xhdl.XSubType#getName <em>Name</em>}</li>
 *   <li>{@link xproject.xhdl.XSubType#getXis <em>Xis</em>}</li>
 * </ul>
 *
 * @see xproject.xhdl.XhdlPackage#getXSubType()
 * @model
 * @generated
 */
public interface XSubType extends XElement
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see xproject.xhdl.XhdlPackage#getXSubType_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link xproject.xhdl.XSubType#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Xis</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Xis</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Xis</em>' reference.
   * @see #setXis(XTypeRef)
   * @see xproject.xhdl.XhdlPackage#getXSubType_Xis()
   * @model
   * @generated
   */
  XTypeRef getXis();

  /**
   * Sets the value of the '{@link xproject.xhdl.XSubType#getXis <em>Xis</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Xis</em>' reference.
   * @see #getXis()
   * @generated
   */
  void setXis(XTypeRef value);

} // XSubType
