/**
 * generated by Xtext 2.15.0
 */
package xproject.web;

import xproject.web.AbstractXHDLWebModule;

/**
 * Use this class to register additional components to be used within the web application.
 */
@SuppressWarnings("all")
public class XHDLWebModule extends AbstractXHDLWebModule {
}
