/*
 * generated by Xtext 2.15.0
 */
package xproject.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import xhdl.ui.internal.XhdlActivator;

public class XHDLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XhdlActivator.getInstance().getInjector("xproject.XHDL");
	}

}
