/*
 * generated by Xtext 2.15.0
 */
package xproject.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import xproject.services.XHDLGrammarAccess;
import xproject.xhdl.XArray;
import xproject.xhdl.XAttribute;
import xproject.xhdl.XPackage;
import xproject.xhdl.XRange;
import xproject.xhdl.XSignal;
import xproject.xhdl.XSubType;
import xproject.xhdl.XType;
import xproject.xhdl.XUnits;
import xproject.xhdl.XhdlPackage;
import xproject.xhdl.xhdl;

@SuppressWarnings("all")
public class XHDLSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private XHDLGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == XhdlPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case XhdlPackage.XARRAY:
				sequence_XArray(context, (XArray) semanticObject); 
				return; 
			case XhdlPackage.XATTRIBUTE:
				sequence_XAttribute(context, (XAttribute) semanticObject); 
				return; 
			case XhdlPackage.XPACKAGE:
				sequence_XPackage(context, (XPackage) semanticObject); 
				return; 
			case XhdlPackage.XRANGE:
				if (rule == grammarAccess.getXElementRule()
						|| rule == grammarAccess.getXTypeRule()) {
					sequence_XRange(context, (XRange) semanticObject); 
					return; 
				}
				else if (rule == grammarAccess.getXRangeRule()) {
					sequence_XRange_XUnits(context, (XRange) semanticObject); 
					return; 
				}
				else break;
			case XhdlPackage.XSIGNAL:
				sequence_XSignal(context, (XSignal) semanticObject); 
				return; 
			case XhdlPackage.XSUB_TYPE:
				sequence_XSubType(context, (XSubType) semanticObject); 
				return; 
			case XhdlPackage.XTYPE:
				sequence_XType(context, (XType) semanticObject); 
				return; 
			case XhdlPackage.XUNITS:
				sequence_XUnits(context, (XUnits) semanticObject); 
				return; 
			case XhdlPackage.XHDL:
				sequence_xhdl(context, (xhdl) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     XElement returns XArray
	 *     XType returns XArray
	 *     XArray returns XArray
	 *
	 * Constraint:
	 *     type=[XType|ID]
	 */
	protected void sequence_XArray(ISerializationContext context, XArray semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, XhdlPackage.Literals.XARRAY__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, XhdlPackage.Literals.XARRAY__TYPE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getXArrayAccess().getTypeXTypeIDTerminalRuleCall_8_0_1(), semanticObject.eGet(XhdlPackage.Literals.XARRAY__TYPE, false));
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     XElement returns XAttribute
	 *     XAttribute returns XAttribute
	 *
	 * Constraint:
	 *     (name=ID type=[XType|ID])
	 */
	protected void sequence_XAttribute(ISerializationContext context, XAttribute semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, XhdlPackage.Literals.XELEMENT__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, XhdlPackage.Literals.XELEMENT__NAME));
			if (transientValues.isValueTransient(semanticObject, XhdlPackage.Literals.XATTRIBUTE__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, XhdlPackage.Literals.XATTRIBUTE__TYPE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getXAttributeAccess().getNameIDTerminalRuleCall_2_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getXAttributeAccess().getTypeXTypeIDTerminalRuleCall_4_0_1(), semanticObject.eGet(XhdlPackage.Literals.XATTRIBUTE__TYPE, false));
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     XPackage returns XPackage
	 *
	 * Constraint:
	 *     (name=ID elements+=XElement*)
	 */
	protected void sequence_XPackage(ISerializationContext context, XPackage semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     XElement returns XRange
	 *     XType returns XRange
	 *
	 * Constraint:
	 *     {XRange}
	 */
	protected void sequence_XRange(ISerializationContext context, XRange semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     XRange returns XRange
	 *
	 * Constraint:
	 *     units+=XUnit*
	 */
	protected void sequence_XRange_XUnits(ISerializationContext context, XRange semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     XElement returns XSignal
	 *     XSignal returns XSignal
	 *
	 * Constraint:
	 *     name=ID
	 */
	protected void sequence_XSignal(ISerializationContext context, XSignal semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, XhdlPackage.Literals.XELEMENT__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, XhdlPackage.Literals.XELEMENT__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getXSignalAccess().getNameIDTerminalRuleCall_2_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     XElement returns XSubType
	 *     XSubType returns XSubType
	 *
	 * Constraint:
	 *     (name=ID is=[XType|ID])
	 */
	protected void sequence_XSubType(ISerializationContext context, XSubType semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, XhdlPackage.Literals.XELEMENT__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, XhdlPackage.Literals.XELEMENT__NAME));
			if (transientValues.isValueTransient(semanticObject, XhdlPackage.Literals.XSUB_TYPE__IS) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, XhdlPackage.Literals.XSUB_TYPE__IS));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getXSubTypeAccess().getNameIDTerminalRuleCall_2_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getXSubTypeAccess().getIsXTypeIDTerminalRuleCall_4_0_1(), semanticObject.eGet(XhdlPackage.Literals.XSUB_TYPE__IS, false));
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     XElement returns XType
	 *     XType returns XType
	 *
	 * Constraint:
	 *     name=ID
	 */
	protected void sequence_XType(ISerializationContext context, XType semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, XhdlPackage.Literals.XELEMENT__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, XhdlPackage.Literals.XELEMENT__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getXTypeAccess().getNameIDTerminalRuleCall_0_2_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     XUnits returns XUnits
	 *
	 * Constraint:
	 *     units+=XUnit*
	 */
	protected void sequence_XUnits(ISerializationContext context, XUnits semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     xhdl returns xhdl
	 *
	 * Constraint:
	 *     packages+=XPackage+
	 */
	protected void sequence_xhdl(ISerializationContext context, xhdl semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
