/**
 * generated by Xtext 2.15.0
 */
package xproject;

import xproject.XHDLStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class XHDLStandaloneSetup extends XHDLStandaloneSetupGenerated {
  public static void doSetup() {
    new XHDLStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
