/*
 * generated by Xtext 2.15.0
 */
package xproject.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link XHDLWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractXHDLWebModule extends DefaultWebModule {

}
